### ISSUE TITLE
MoPub-FacebookAudienceNetwork-Adapters below 4.99 can't compile

### ISSUE THREAD

**Issue by SmartHbdev** [mopub/mopub-ios-mediation#101]
Hi,

After a pod clean cache i have notice a error in Facebook Adapter.

You have add FBAdIconView *iconView (and many other lines) in version 4.99 but i see them in MoPub-FacebookAudienceNetwork-Adapters (4.28.1.3). I can't build my app anymore since this Facebook SDK version (4.28) don't find FBAdIconView.

To reproduce just add this line in pod:
   
    pod 'MoPub-FacebookAudienceNetwork-Adapters' , '<4.99'

Best regards

**Comment by chauduyphanvu1** [comment]
@SmartHbdev, currently our CocoaPods deploys do not fully let publishers download past versions of adapters. It will always get the latest on master. This is something we plan to work on supporting in the future. Right now, even though you are using `<4.99`, what you are effectively getting is the latest [adapter version](https://github.com/mopub/mopub-ios-mediation/blob/master/FacebookAudienceNetwork/CHANGELOG.md) (5.0.0 as of this writing). That explains why you are seeing code for the `FBAdIconView`, which is in 5.0.x.y (it got added in the 4.99.x.y release).

To get adapters that were certified with FB SDK version 4.28.x, you will have to get the binaries from this GitHub repo via historical releases. Here's one of the 4.28.x.y releases I could find: https://github.com/mopub/mopub-ios-mediation/tree/22a9eb8539fa8d505d6475bbfc8ef0d302b488a2/FacebookAudienceNetwork.

**Comment by SmartHbdev** [comment]
@chauduyphanvu1 thanks for you quick reply. I want to stay on pod, maybe i should upgrade to v5. Is it safe to update to v5 or must i change some code part ?

I can't find any information if something changed for us.

**Comment by chauduyphanvu1** [comment]
The 5.0.0.0 adapters have been certified with Facebook 5.0.0, so it is safe to upgrade. On the iOS side, there should be no implementation change required from publishers, since all the work was done in the adapters to maintain backward compatibility. More info is available in the [changelog](https://github.com/mopub/mopub-ios-mediation/blob/master/FacebookAudienceNetwork/CHANGELOG.md).

Let us know if you have any questions!

**Comment by SmartHbdev** [comment]
Thanks
