### ISSUE TITLE
AdMob Banner adapter crashed on MoPub 5.4.0

### ISSUE THREAD

**Issue by adxcorp** [mopub/mopub-ios-mediation#107]
In MPGoogleAdMobBannerCustomEvent class, occur crash in this following line.

self.adBannerView = [[GADBannerView alloc] initWithFrame:CGRectZero];

It occurs infrequently,
I guess in this case MPBannerCustomEvent init does not called in main UI thread.

**Comment by chauduyphanvu1** [comment]
@adxcorp - do you have the stack trace? Could you send us a mini sample project that reproduces it (if you can repro it personally)?

**Comment by adxcorp** [comment]
I got another adapter's stack stace today, but this is same issue, I guess.
It is hard to reproduce. I saw this crash only twice whole week and don't know reproducing step.

Main Thread Checker: UI API called on a background thread: -[UIWebView initWithFrame:]
PID: 2364, TID: 460556, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   ADXLibrary_iOSSample                0x00000001015b0138 -[ZZAdBaseHelper getUserAgent] + 84
5   ADXLibrary_iOSSample                0x00000001015b783c -[ZZAdManager initWithConfig:] + 100
6   ADXLibrary_iOSSample                0x00000001015bbcdc +[ZZAdSettings setConfig:] + 88
7   ADXLibrary_iOSSample                0x0000000100f3b81c -[BatMobiBannerCustomEvent requestAdWithSize:customEventInfo:] + 788
8   ADXLibrary_iOSSample                0x0000000100fba4d8 -[MPBannerCustomEvent requestAdWithSize:customEventInfo:adMarkup:] + 120
9   ADXLibrary_iOSSample                0x0000000100fbac78 -[MPBannerCustomEventAdapter getAdWithConfiguration:targeting:containerSize:] + 788
10  ADXLibrary_iOSSample                0x0000000100fbbfec -[MPBaseBannerAdapter _getAdWithConfiguration:targeting:containerSize:] + 172
11  ADXLibrary_iOSSample                0x0000000100fb85c0 -[MPBannerAdManager fetchAdWithConfiguration:] + 1596
12  ADXLibrary_iOSSample                0x0000000100fb9464 -[MPBannerAdManager adapter:didFailToLoadAdWithError:] + 752
13  ADXLibrary_iOSSample                0x0000000100fbb54c -[MPBannerCustomEventAdapter bannerCustomEvent:didFailToLoadAdWithError:] + 164
14  ADXLibrary_iOSSample                0x0000000100f72290 -[YeahMobiBannerCustomEvent CTAdView:didFailToReceiveAdWithError:] + 228
15  ADXLibrary_iOSSample                0x0000000101094c94 __71-[CTService getMRAIDBannerAdWithSlot:delegate:adSize:container:isTest:]_block_invoke + 576
16  libdispatch.dylib                   0x00000001021bf840 _dispatch_call_block_and_release + 24
17  libdispatch.dylib                   0x00000001021c0de4 _dispatch_client_callout + 16
18  libdispatch.dylib                   0x00000001021c3cac _dispatch_queue_override_invoke + 888
19  libdispatch.dylib                   0x00000001021d21f8 _dispatch_root_queue_drain + 376
20  libdispatch.dylib                   0x00000001021d2be4 _dispatch_worker_thread2 + 156
21  libsystem_pthread.dylib             0x0000000193dd6190 _pthread_wqthread + 472
22  libsystem_pthread.dylib             0x0000000193dd8d00 start_wqthread + 4
2018-10-23 20:46:38.210812+0900 ADXLibrary_iOSSample[2364:460556] [reports] Main Thread Checker: UI API called on a background thread: -[UIWebView initWithFrame:]
PID: 2364, TID: 460556, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   ADXLibrary_iOSSample                0x00000001015b0138 -[ZZAdBaseHelper getUserAgent] + 84
5   ADXLibrary_iOSSample                0x00000001015b783c -[ZZAdManager initWithConfig:] + 100
6   ADXLibrary_iOSSample                0x00000001015bbcdc +[ZZAdSettings setConfig:] + 88
7   ADXLibrary_iOSSample                0x0000000100f3b81c -[BatMobiBannerCustomEvent requestAdWithSize:customEventInfo:] + 788
8   ADXLibrary_iOSSample                0x0000000100fba4d8 -[MPBannerCustomEvent requestAdWithSize:customEventInfo:adMarkup:] + 120
9   ADXLibrary_iOSSample                0x0000000100fbac78 -[MPBannerCustomEventAdapter getAdWithConfiguration:targeting:containerSize:] + 788
10  ADXLibrary_iOSSample                0x0000000100fbbfec -[MPBaseBannerAdapter _getAdWithConfiguration:targeting:containerSize:] + 172
11  ADXLibrary_iOSSample                0x0000000100fb85c0 -[MPBannerAdManager fetchAdWithConfiguration:] + 1596
12  ADXLibrary_iOSSample                0x0000000100fb9464 -[MPBannerAdManager adapter:didFailToLoadAdWithError:] + 752
13  ADXLibrary_iOSSample                0x0000000100fbb54c -[MPBannerCustomEventAdapter bannerCustomEvent:didFailToLoadAdWithError:] + 164
14  ADXLibrary_iOSSample                0x0000000100f72290 -[YeahMobiBannerCustomEvent CTAdView:didFailToReceiveAdWithError:] + 228
15  ADXLibrary_iOSSample                0x0000000101094c94 __71-[CTService getMRAIDBannerAdWithSlot:delegate:adSize:container:isTest:]_block_invoke + 576
16  libdispatch.dylib                   0x00000001021bf840 _dispatch_call_block_and_release + 24
17  libdispatch.dylib                   0x00000001021c0de4 _dispatch_client_callout + 16
18  libdispatch.dylib                   0x00000001021c3cac _dispatch_queue_override_invoke + 888
19  libdispatch.dylib                   0x00000001021d21f8 _dispatch_root_queue_drain + 376
20  libdispatch.dylib                   0x00000001021d2be4 _dispatch_worker_thread2 + 156
21  libsystem_pthread.dylib             0x0000000193dd6190 _pthread_wqthread + 472
22  libsystem_pthread.dylib             0x0000000193dd8d00 start_wqthread + 4
2018-10-23 20:46:39.061449+0900 ADXLibrary_iOSSample[2364:460556] void _WebThreadLock(), 0x105594000: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...

**Comment by chauduyphanvu1** [comment]
@adxcorp - thanks, we'll investigate this stack trace. All of our UI WebView operations for ads should already be happening on the main thread. This might be an edge case with a select few third-party custom events that we don't support/certifty. I'd also recommend raising the issue with the respective ad network whose custom events you are using in your app.

Do you still see the crash? In the meantime, if you ever reproduce the crash in your own app, feel free to send us a mini version of it!

**Comment by adxcorp** [comment]
It also occur Google mediation adapter that provided by mopub.

Please re-check it.

**Comment by chauduyphanvu1** [comment]
We regularly certify all adapters on our official repositories and do not see this crash with our tests. Do you mind sharing your implementation via a mini sample app with which you saw the crash? Thanks!

**Comment by chauduyphanvu1** [comment]
Closing as irreproducible.
