### ISSUE TITLE
"alnullable" typo, how you test this even?

### ISSUE THREAD

**Issue by KAMIKAZEUA** [mopub/mopub-ios-mediation#123]
https://github.com/mopub/mopub-ios-mediation/blob/master/AppLovin/AppLovinInterstitialCustomEvent.m#L221

**Comment by chauduyphanvu1** [comment]
Thanks for the confirmation, @thomasmso! @KAMIKAZEUA, please watch for the new adapters that should resolve this.

**Comment by chauduyphanvu1** [comment]
Resolved in https://github.com/mopub/mopub-ios-mediation/commit/faf623025c97fef6e4a5b71c65dc199c14b77646.
