### ISSUE TITLE
 Crash when loading AppLovin adapter

### ISSUE THREAD

**Issue by Volodymyr-Klymenko** [mopub/mopub-ios-mediation#125]
1. Crash when loading banner for AppLovin adapter

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Banner
    * **Platform** (*Android, iOS, Unity*)
        > iOS
    * **MoPub SDK Version**
        > 5.4.1
    * **Mediation SDK Name & Version**
        > AppLovin 6.1.0
    * **Mediation Adapter Version**
        > 5.1.2.1
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > 4a0031a9c2d14707aa37d937234c6936
    * **Device model and OS Version**
        > 12
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Do this.
        > 2. Do that.
    * **Observed behavior**
        > Crash
    * **Expected behavior** (if known)
        > no crash
    * **Evidence** (if available)
        > 
![screen shot](https://user-images.githubusercontent.com/45468910/49399029-ccc57a00-f748-11e8-9b42-5689d3247ce7.png)

**Comment by thomasmso** [comment]
@Volodymyr-Klymenko - Can you attach a screenshot of the crash's error message and/or the debug area? That would be very helpful. Thanks!

**Comment by Volodymyr-Klymenko** [comment]
@chauduyphanvu1 
![screen shot](https://user-images.githubusercontent.com/45468910/49401965-3ea1c180-f751-11e8-9633-3c0645982bd5.png)

**Comment by thomasmso** [comment]
This is pretty weird - are you running it on a simulator? If you run it on a device, do you still get the same issue?

**Comment by Volodymyr-Klymenko** [comment]
Tested both. It's just depends on Ad Unit ID. Because when I used another, it's worked.

**Comment by thomasmso** [comment]
Ok, then @chauduyphanvu1 might have more insight on that

**Comment by chauduyphanvu1** [comment]
@Volodymyr-Klymenko - I'm not seeing any crash from those adapter & SDK versions and that ad unit ID. We need to either know how you integrated the adapters or see a mini sample project that you used to trigger this crash. Could you attach either of those items? Thanks!

**Comment by Volodymyr-Klymenko** [comment]
@chauduyphanvu1 give me your created sample project on which you can't reproduce this and I will show you.

**Comment by Volodymyr-Klymenko** [comment]
My project is MRC, so I fixed this by adding `-fobjc-arc` flag to adapters classes.

**Comment by mopubmediation** [comment]
@Volodymyr-Klymenko - glad to hear that you've identified the root cause and a resolution path. Let us know if you need any assistance.

**Comment by Volodymyr-Klymenko** [comment]
@mopubmediation Why this is not indicated in the documentation ?

**Comment by chauduyphanvu1** [comment]
@Volodymyr-Klymenko - our SDK codebase assumes an ARC environment, which is why it's not documented. I'll go ahead and note that down, though!

**Comment by chauduyphanvu1** [comment]
@Volodymyr-Klymenko - it's documented here: https://developers.mopub.com/docs/ios/getting-started/#for-applications-that-use-mrc. Let us know if you need anything else!
