### ISSUE TITLE
Add ability to pass test-device-id's to Admob

### ISSUE THREAD

**Issue by ogres** [mopub/mopub-ios-mediation#126]
I don't see a way to pass identifier of test devices to Admob, we can only change adChoicesPosition MPGoogleAdMobNativeCustomEvent.

Would be nice if we could add test devices, to make sure we actually get test ads.

These are the versions.

  - MoPub-AdMob-Adapters (7.36.0.0):
    - Google-Mobile-Ads-SDK (= 7.36.0)
    - mopub-ios-sdk (~> 5.0)
  - mopub-ios-sdk (5.4.1):
    - mopub-ios-sdk/MoPubSDK (= 5.4.1)

**Comment by ogres** [comment]
Yes, it might be okay for banners, but definitely not for native ads.
I see warning logs in console about missing test device identifiers.

**Comment by chauduyphanvu1** [comment]
@maninomula - what are your thoughts on supporting this use case? If you want to send over a PR, you can utilize MoPub's "localExtras" NSDict to store and extract the device's UDID and pass that to Google's test ad API.

**Comment by maninomula** [comment]
Hi @chauduyphanvu1 and @ogres ,

Will be sending a PR with this feature soon.

Thanks

**Comment by chauduyphanvu1** [comment]
@maninomula - Do you have an ETA for when this would be done? Thanks!

**Comment by maninomula** [comment]
Hi @chauduyphanvu1 ,
Sent a PR [here](https://github.com/mopub/mopub-ios-mediation/pull/137).

**Comment by chauduyphanvu1** [comment]
@ogres - this is done in https://github.com/mopub/mopub-ios-mediation/commit/6c1f3b54ee71bfc0d88364da6c77d88738212ee6 (hanks @maninomula!). Running `pod 'MoPub-AdMob-Adapters', '7.37.0.0'` will get you the update.
