### ISSUE TITLE
userInteractionEnabled should be disabled for GADOAdChoicesView

### ISSUE THREAD

**Issue by ogres** [mopub/mopub-ios-mediation#127]
I am seeing following logs in Console from Admob mediation ( for native ads ):

> <Google> User interactions must be disabled on the asset view to enable click handling.
userInteractionEnabled has been set to NO on <GADOAdChoicesView: 0x7b50001eb200; frame = (0 0; 0 0); userInteractionEnabled = NO; layer = <CALayer: 0x7b08001f83c0>>.

userInteractionEnabled should be disabled for GADOAdChoicesView to let Admob properly handle it.

Here are the version numbers:

MoPub-AdMob-Adapters (7.36.0.0):
Google-Mobile-Ads-SDK (= 7.36.0)
mopub-ios-sdk (~> 5.0)
mopub-ios-sdk (5.4.1):
mopub-ios-sdk/MoPubSDK (= 5.4.1)

**Comment by fcheung1** [comment]
@maninomula can you review this issue, and either provide feedback or submit a PR?

**Comment by maninomula** [comment]
Hi Fred, Taking a look in to it. Will get back as soon as I found something.

**Comment by fcheung1** [comment]
Thanks @maninomula! 

@ogres - My name is Fred and I work on the MoPub team managing our certified network relationships. Thanks for reaching out and surfacing your concern! Mani (cc'ed) is on the Google team and will provide feedback shortly.

**Comment by maninomula** [comment]
Hi @fcheung1,

I opened a PR [here](https://github.com/mopub/mopub-ios-mediation/pull/132) which should solve this issue.

Thanks

**Comment by chauduyphanvu1** [comment]
Released via https://github.com/mopub/mopub-ios-mediation/commit/742318c34a91e899e6b1242a56f019eaca79a83f.

**Comment by ogres** [comment]
Thank you!
