### ISSUE TITLE
Documentation is not clear

### ISSUE THREAD

**Issue by KAMIKAZEUA** [mopub/mopub-ios-mediation#130]
https://developers.mopub.com/docs/ios/rewarded-video/#4-show-the-rewarded-video

In the current docs there are code for presenting rewarded video: 
`[MPRewardedVideo presentRewardedVideoAdForAdUnitID:@"YOUR_AD_UNIT_ID" fromViewController:self];`

But there is not such method actually.

It's different in then SDK: 
`+ (void)presentRewardedVideoAdForAdUnitID:(NSString *)adUnitID fromViewController:(UIViewController *)viewController withReward:(MPRewardedVideoReward *)reward;
`

https://github.com/mopub/mopub-ios-sdk/blob/master/MoPubSDK/RewardedVideo/MPRewardedVideo.h#L154

Notice another parameter should be passed, but it's not indicated in docs and how it exactly should be used, no examples.

**Comment by dravyan** [comment]
Hello @KAMIKAZEUA,
 Thank you for bringing that to our attention. We will look into it and update our documentation to use updated method parameters.

Thanks,
Dravya Nataraj
MoPub SDK Team

**Comment by chauduyphanvu1** [comment]
@KAMIKAZEUA - I prepared a documentation update that should be live soon. Until then, please reference our iOS sample app's usage of that method at https://github.com/mopub/mopub-ios-sdk/blob/master/MoPubSampleApp/Controllers/MPRewardedVideoAdDetailViewController.m#L95. The `MPRewardedVideoReward` can be extracted from the `[MPRewardedVideo availableRewardsForAdUnitID:self.info.ID]` NSArray of available rewards. You do not have to pass the custom data if there's no use case for it.

**Comment by chauduyphanvu1** [comment]
@KAMIKAZEUA - the documentation has been updated to reflect the proper usage of `presentRewardedVideoAdForAdUnitID`.

**Comment by Volodymyr-Klymenko** [comment]
I can't see any changes now.

**Comment by KAMIKAZEUA** [comment]
@chauduyphanvu1 I can't see any changes now.

**Comment by chauduyphanvu1** [comment]
@KAMIKAZEUA - it should be live now. The actual deploy might have taken some time to finish globally.
