### ISSUE TITLE
The podspecs are configured to always bring the latest master code 

### ISSUE THREAD

**Issue by stopiccot** [mopub/mopub-ios-mediation#134]
Reopening #76. Please do a proper fix it's not that hard use git tags as described in cocoapods manual https://guides.cocoapods.org/syntax/podspec.html

**Comment by chauduyphanvu1** [comment]
Hello, thanks for bringing this up. We are indeed going to do tagged releases. A few internal details are in the work, and as soon as they are finalized, we will be rolling this functionality out.

Vu Chau
MoPub SDK Team

**Comment by rsatrasala** [comment]
Hello @stopiccot please follow #76 for further updates. Closing this issue as a duplicate.

**Comment by stopiccot** [comment]
Last time #76 was closed without actually fixing the issue. I suggest to close issues when they are actually resolved.
