### ISSUE TITLE
Please update Admob SDK to 7.37.0

### ISSUE THREAD

**Issue by shabbirv** [mopub/mopub-ios-mediation#135]
1. **What is the issue?**
    > The current supported release of the Google Mobile Ads SDK has a pretty bad crash: https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/ios/e_P7wCxTtsM.

Can we update the SDK to the latest (7.37.0)

**Comment by chauduyphanvu1** [comment]
Thanks for the request. 7.37.0 is not certified with MoPub yet, so we'll take a look and test the adapters with it before we can say if publishers should/could update.

Vu Chau
MoPub SDK Team

**Comment by rsatrasala** [comment]
@shabbirv Please watch our [Mediation Integration Tool](https://developers.mopub.com/docs/mediation/integrate/) page  for additional updates.
