### ISSUE TITLE
Installing old MoPub-AdMob-Adapters via pods

### ISSUE THREAD

**Issue by TimFowle** [mopub/mopub-ios-mediation#162]
1. **What is the issue?**
    Pulling old versions results in the latest being installed

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > N/A
    * **Platform** (*Android, iOS, Unity*)
        > iOS
    * **MoPub SDK Version**
        > 5.3.0
    * **Mediation SDK Name & Version**
        > AdMob 7.31.0
    * **Mediation Adapter Version**
        > 7.31.0.2
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > N/A
    * **Device model and OS Version**
        > N/A
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Add following to podfile:
pod ‘MoPub-AdMob-Adapters’, ‘7.31.0.2’
        > 2. pod install
    * **Observed behavior**
        > GoogleAdMobAdapterConfiguration.m contains latest version 7.37.0.4
    * **Expected behavior** (if known)
        > GoogleAdMobAdapterConfiguration.m should not exist as not part of 7.31.0.2
    * **Evidence** (if available)
        > pod install --verbose shows the following:
Git download
/usr/bin/git clone https://github.com/mopub/mopub-ios-mediation.git /var/folders/gk/rqcp8h2j10b4fbycbm_0hdp40000gp/T/d20190211-48260-1l0l0b0 --template= Cloning into '/var/folders/gk/rqcp8h2j10b4fbycbm_0hdp40000gp/T/d20190211-48260-1l0l0b0'... /usr/bin/git -C /var/folders/gk/rqcp8h2j10b4fbycbm_0hdp40000gp/T/d20190211-48260-1l0l0b0 checkout --quiet master
Copying MoPub-AdMob-Adapters from /Users/jenkins/Library/Caches/CocoaPods/Pods/Release/MoPub-AdMob-Adapters/7.31.0.2-e0a58 to Pods/MoPub-AdMob-Adapters

**Comment by dravyan** [comment]
HI @TimFowle ,
  Thank you for reporting this to us. We looked into it and have updated the pods and released `7.31.0.3` to pull right version of adapter files and SDK. Please follow below steps for the fix -
* Add following to podfile:
  pod ‘MoPub-AdMob-Adapters’, ‘7.31.0.3’
* pod install

Thanks,
Dravya Nataraj
MoPub SDK Team
