### ISSUE TITLE
GoogleAdMobAdapterConfiguration : Incorrect class name

### ISSUE THREAD

**Issue by Waserk** [mopub/mopub-ios-mediation#166]
Hello,

It seems that `GoogleAdMobAdapterConfiguration` is not supposed to be named this way.
In the Unity SDK, it register the prefix as `MPGoogle`, and when it tries to initialize admob adapter configuration class, it looks for `MPGoogleAdapterConfiguration` settings, however this results in network settings not passed to the adapter.

I have renamed the `GoogleAdMobAdapterConfiguration` to `MPGoogleAdapterConfiguration` and it has fixed the issue.

Best,

**Comment by chauduyphanvu1** [comment]
@Waserk - thanks for letting us know! We'll take a look and see what can be done to resolve the issue.

Vu Chau
MoPub SDK Team

**Comment by chauduyphanvu1** [comment]
This has been fixed and will be deployed in the upcoming Unity SDK release.

**Comment by chauduyphanvu1** [comment]
@Waserk - This issue should be fixed as of v5.6.0 of the Unity SDK. Please update to that version and let us know if you continue seeing the issue!
