### ISSUE TITLE
IronSourceRewardedVideoCustomEvent crashing on loading failure

### ISSUE THREAD

**Issue by Khronoss** [mopub/mopub-ios-mediation#169]
1. **What is the issue?**
    > For IronSource's adapter, there is a log line after `[strongDelegate rewardedVideoDidFailToLoadAdForCustomEvent:self error:error]` which makes a dangling pointer exception.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [ ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Rewarded Video
    * **Platform** (*Android, iOS, Unity*)
        > iOS
    * **MoPub SDK Version**
        > 5.5.0
    * **Mediation SDK Name & Version**
        > 
    * **Mediation Adapter Version**
        > MoPub-IronSource-Adapters 6.8.1.0.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > 20793e95371747f0b0db41f39f4c80d5
    * **Device model and OS Version**
        > any iPhone any OS
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Launch the app with given UnitID.
        > 2. IronSource should fail at downloading the ad.
    * **Observed behavior**
        > Application is crashing because the adapter puts a log after it calls its delegate's methode, witch set the adapter to nil (dangling pointer)
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > 
<img width="949" alt="capture d ecran 2019-02-27 a 16 26 17" src="https://user-images.githubusercontent.com/4353229/53505675-a0ee3200-3ab4-11e9-923b-9e63ebe3c94d.png">

.

**Comment by dravyan** [comment]
Hi @Khronoss,
 Thank you for reporting the issue. I am not able to replicate the issue on our end with mopub sample app and IronSource adapters. I do not see any crash/issue as shown in the logs below. To investigate the issue further, could you please provide the app or the sample project that you are seeing this behavior in? 

```
[MoPub][MPRewardedVideoAdapter] Looking for custom event class named IronSourceRewardedVideoCustomEvent.
   2019-02-27 20:23:07.446529-0800 Canary[18329:14861991] 
[MoPub][IronSourceRewardedVideoCustomEvent][1172527] Adapter IronSourceRewardedVideoCustomEvent attempting to load ad
2019-02-27 20:23:07.446728-0800 Canary[18329:14861991] 
[MoPub][IronSourceRewardedVideoCustomEvent] IronSource rewarded video ad was not available
2019-02-27 20:23:07.446965-0800 Canary[18329:14861991] 
[MoPub][IronSourceRewardedVideoCustomEvent][1172527] Adapter IronSourceRewardedVideoCustomEvent failed to load ad: (0) IronSource adapter failed to request rewarded video
```

Thanks,
Dravya Nataraj
MoPub SDKTeam

**Comment by Khronoss** [comment]
Hi @dravyan,
Thank you for your answer. Unfortunately, I'm not able to give you access to the full project but I made a minimalist sample with what I managed to reproduce the crash.
You can find it [here on github](https://github.com/Khronoss/MPIS_sample_project)

The project uses Podfile and Podfile.lock so you'll just have to run `pod install` after cloning the project.
The IronSourceAdapter's version used is the most recent one

To reproduce the crash you only have to launch the application and wait a few seconds for IronSource to be notified that the Ad Availability has changed through `- (void)rewardedVideoHasChangedAvailability:(BOOL)available instanceId:(NSString *)instanceId` method

I also added a screen recording to the root of the repository so that you can see what is happening to me if you don't manage to reproduce

Have a nice day !
Anthony

**Comment by dravyan** [comment]
Thanks @Khronoss. I am still not able to replicate the crash on my end. But the video you have shared is helpful. We will look into it and see what can be done to resolve the issue.

Dravya Nataraj
MoPub SDKTeam

**Comment by dravyan** [comment]
This issue has been fixed in  latest version of IronSource adapters 6.8.1.0.1.

**Comment by Khronoss** [comment]
Hi @dravyan , thank you for applying a fix based only on a trust you built on me !
I just tested and did not have the crash again, but I didn't even made it to the `rewardedVideoHasChangedAvailability:instanceId:` error scenario... So I'll keep an eye on it and come back to you if needed

Thank you again 👍
