### ISSUE TITLE
AppLovin - `reward` overriding itself? 

### ISSUE THREAD

**Issue by chauduyphanvu1** [mopub/mopub-ios-mediation#184]
1. **What is the issue?**
Strange compile-time warning about recursion from the AppLovin iOS SDK:

    > Instance method 'reward' in category from mopub-ios-sdk/Canary/Pods/AppLovinSDK/applovin-ios-sdk-6.5.4/AppLovinSDK.framework/AppLovinSDK(ALMediationAdapter.o) overrides method from class in mopub-ios-sdk/Canary/Pods/AppLovinSDK/applovin-ios-sdk-6.5.4/AppLovinSDK.framework/AppLovinSDK(ALMediationAdapter.o)

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > N/A
    * **Platform** (*Android, iOS, Unity*)
        > iOS
    * **MoPub SDK Version**
        > N/A
    * **Mediation SDK Name & Version**
        > AppLovin SDK 6.5.4
    * **Mediation Adapter Version**
        > 6.5.4.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > N/A
    * **Device model and OS Version**
        > N/A (compile-time warning)
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Integrate AppLovin
        > 2. Compile
    * **Observed behavior**
        > Warning above
    * **Expected behavior** (if known)
        > No warning
    * **Evidence** (if available)
        > N/A

**Comment by chauduyphanvu1** [comment]
@thomasmso, could you help look into this issue? Thank you!

**Comment by thomasmso** [comment]
Hi @chauduyphanvu1 - We're aware of the warnings - it will be fixed in our iOS SDK 6.6.0 update in the next couple days. Will keep you updated. Sorry for the inconvenience!

**Comment by thomasmso** [comment]
Hi @chauduyphanvu1 - our iOS SDK 6.6.0 is live now. Thanks!

**Comment by chauduyphanvu1** [comment]
@thomasmso - thank you! Will include it in the current certification.

**Comment by chauduyphanvu1** [comment]
Resolved with AppLovin SDK 6.6.0 pulled in via https://github.com/mopub/mopub-ios-mediation/commit/bee5a7488e0c40db6f7ad9b085c98d32db02414a.
