### ISSUE TITLE
AdMob Spec not working

### ISSUE THREAD

**Issue by rscholtes** [mopub/mopub-ios-mediation#19]
When using:

pod 'MoPub-AdMob-Adapters'

with use_frameworks! (i think is the problem), the compilation of the adapter fails.

on multiple places
#if __has_include(<MoPub/MoPub.h>) is wrongly spelled and spelled with spaces like:
#if __has_include(<MoPub / MoPub.h>), so this include wont work.

and the MPGoogleAdMobRewardedVideoCustomEvent.h does not check for this __include, but just has 
#import "MPRewardedVideoCustomEvent.h"
which fails.

Removing the spaces and adding the __has_include will allow for a successfull build.

**Comment by alanchen** [comment]
I got the same problem

**Comment by PoojaChirp** [comment]
Thank you for inputs @rscholtes, we have added these changes to our adapters.
