### ISSUE TITLE
TapJoy adapters do not work with MoPub 5.5

### ISSUE THREAD

**Issue by stopiccot** [mopub/mopub-ios-mediation#197]
Just to let you know guys MoPub-TapJoy-Adapters cocoapod version 12.3.1.0 have a dependency on mopub-ios-sdk/Core cocoapod declared as `~> 5.5`. So MoPub 5.5 should work. But in reality compilation fails with an error:
```
MoPub-TapJoy-Adapters/Tapjoy/TapjoyAdapterConfiguration.m:109:5: Unknown type name 'MPBLogLevel'; did you mean 'MPLogLevel'?
```

**Comment by dravyan** [comment]
@stopiccot , thank you for reporting this issue. This has been fixed in the latest Tapjoy Adapter version [12.3.1.1](https://github.com/mopub/mopub-ios-mediation/blob/master/Tapjoy/CHANGELOG.md). Please update to the latest version.

Thanks,
Dravya Nataraj
MoPub SDK Team
