### ISSUE TITLE
modulemap doesn't create automatically on CocoaPods

### ISSUE THREAD

**Issue by giginet** [mopub/mopub-ios-mediation#228]
1. **What is the issue?**

Provided podspecs doesn't generate modulemaps automatically, so we need to specify `modular_headers` on `Podfile` to integrate adapters to Swift projects.

```ruby
pod 'Mopub-AdMob-Adapters', modular_headers: true
```

This configuration is needed on `*.podspec`. However podspecs are not public. So I can't change.

```ruby
spec.pod_target_xcconfig = {
  'DEFINES_MODULE' => 'YES',
}
```

See Modular Headers section on this entry http://blog.cocoapods.org/CocoaPods-1.5.0/

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > -
    * **Platform** (*Android, iOS, Unity*)
        > iOS
    * **MoPub SDK Version**
        > 5.9.0
    * **Mediation SDK Name & Version**
        > Cuirrent master
    * **Mediation Adapter Version**
        > Current master
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > -
    * **Device model and OS Version**
        > -
    * **Steps to reproduce the issue** (include integration steps if not standard)

In the situation creating own framework it depends on MoPub-AdMob-Adapters on Swift, modulemap is not generated so it raises error.

```ruby
pod 'Mopub-AdMob-Adapters'
```

```console
$ pod install
The Swift pod `MyAdSDK` depends upon `MoPub-AdMob-Adapters`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

    * **Observed behavior**
        > -
    * **Expected behavior** (if known)
        > -
        > -

**Comment by dravyan** [comment]
@giginet, thanks for reporting. We recommend updating the podfile to use `modular_headers`. 
But I relay this information internally and see what we can do. Thank you for your feedback.

Thanks,
Dravya Nataraj
MoPub Team
