### ISSUE TITLE
Google AdMob git tags missing

### ISSUE THREAD

**Issue by s23tang** [mopub/mopub-ios-mediation#229]
1. **What is the issue?**
At some point in the recent past AdMob tags have been removed from GIT. Looking at GIT tags we cannot find `AdMob-*`.

   It doesn't seem like the ad network is deprecated since https://developers.mopub.com/publishers/mediation/networks/google/ still exists with the instructions, **however** the tags also seem to be missing from [Android mediation](https://github.com/mopub/mopub-android-mediation).

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        N/A
    * **Platform** (*Android, iOS, Unity*)
        Android and iOS git repos
    * **MoPub SDK Version**
        N/A
    * **Mediation SDK Name & Version**
        Google AdMob all versions
    * **Mediation Adapter Version**
        Google AdMob all versions
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        N/A
    * **Device model and OS Version**
        N/A
    * **Steps to reproduce the issue** (include integration steps if not standard)
        1. Navigate to https://github.com/mopub/mopub-ios-mediation (or clone the repo)
        2. Get list of git tags 
        3. `AdMob-*` does not exist
    * **Observed behavior**
        All AdMob tags are missing in git for both iOS and Android
    * **Expected behavior** (if known)
        All AdMob tags in git for both iOS and Android
    * **Evidence** (if available)
        See https://github.com/mopub/mopub-ios-mediation and https://github.com/mopub/mopub-android-mediation tags list

**Comment by dravyan** [comment]
@s23tang, thank you for reporting. We will look into this. Meanwhile, you can use the command `$ git tag -l admob-*` or refer to the [releases tab](https://github.com/mopub/mopub-ios-mediation/tags) to fetch the list of tags available for AdMob.

Thanks,
Dravya Nataraj
MoPub Team

**Comment by rsatrasala** [comment]
Closing it because this seems like a github related problem and we cannot resolve. Please use the alternative approach provided
