### ISSUE TITLE
Unable to change AdMob GDPR consent after SDK init

### ISSUE THREAD

**Issue by silviosav-SEGA-HARDlight** [mopub/mopub-ios-mediation#239]
1. **What is the issue?**
    > Not possible to change NPA after SDK init.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x ] I searched https://developers.mopub.com/ and found no answer.
    - [ x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > All
    * **Platform** (*Android, iOS, Unity*)
        > iOS
    * **MoPub SDK Version**
        > 5.9.0
    * **Mediation SDK Name & Version**
        > pod 'MoPub-AdMob-Adapters', '7.52.0.0'
    * **Mediation Adapter Version**
        > Provide the data here
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > 
    * **Device model and OS Version**
        > All iOS
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Initialize the SDK with/without the AdMob GDPR consent.
        > 2. Try to change the AdMob GDPR consent after.
    * **Observed behavior**
        > New consent applies after app restart, also in case the user revoked the GDPR consent!
    * **Expected behavior** (if known)
        > There should be a way to change the GDPR consent after initialization
    * **Evidence** (if available)
        > I've seen this issue to be already solved on Android in one of the latest adapter version but on iOS the setNpaString method is not exposed into the GoogleAdMobAdapterConfiguration header and so it can't be used.

**Comment by chauduyphanvu** [comment]
@silviosav-SEGA-HARDlight, thanks for letting us know! Let me take a look and see what we can do here.

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
@silviosav-SEGA-HARDlight, let us know if this is something you are looking for:

<img width="1023" alt="Screen Shot 2019-11-18 at 5 39 02 PM" src="https://user-images.githubusercontent.com/25616035/69100071-563d8d00-0a2a-11ea-841c-54d30ccf6614.png">

With that change, you would be able to call `setNpaString:` from anywhere independent of the initialization of the MoPub SDK. If you want to reset the npa, you can pass in a `nil` or an empty String.

**Comment by silviosav-SEGA-HARDlight** [comment]
@chauduyphanvu, yes this is what I'm looking for. When will it be released?

**Comment by chauduyphanvu** [comment]
@silviosav-SEGA-HARDlight, thanks! The release should be some time this week.

**Comment by chauduyphanvu** [comment]
@silviosav-SEGA-HARDlight, this is now supported in https://github.com/mopub/mopub-ios-mediation/commit/bbfcfccf00ee3aa9954d5c9b6dda48666271a778. A release to CocoaPods is in progress so check back in a few minutes.
