### ISSUE TITLE
Please update Admob SDK to 7.53.1

### ISSUE THREAD

**Issue by JohnnyTseng** [mopub/mopub-ios-mediation#246]
1. **What is the issue?**
Mopub Admob Adapter does not support `Google-Mobile-Ads-SDK` 7.53.1 yet

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**

https://developers.google.com/admob/ios/rel-notes

The Google-Mobile-Ads-SDK is `7.53.1` now, includes a fix
`Native ads: Fixed a bug where a UI API was called on a background thread.`
but MoPub admob adapter currently only supports 7.52.0

Would you support the latest SDK? 
Thank you

**Comment by chauduyphanvu** [comment]
@JohnnyTseng, thanks for getting in touch! Look for the new certified Mobile Ads SDK version soon!

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
This is done in https://github.com/mopub/mopub-ios-mediation/commit/eeca3b2ec8b5c9de7dd38c562b8a49d5e6b32966.
