### ISSUE TITLE
Use of undeclared identifier 'MOPUBErrorVideoPlayerFailedToPlay'

### ISSUE THREAD

**Issue by dylancompanjen** [mopub/mopub-ios-mediation#263]
1. **What is the issue?**
    Xcode build fails after adding pod: MoPub-Vungle-Adapters. It will show the error: Use of undeclared identifier 'MOPUBErrorVideoPlayerFailedToPlay' (coming from VungleRouter.m)
    I just found out it's due to 'GoogleMobileAdsMediationMoPub' being dependant on an older MoPub version.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Platform** (*Android, iOS, Unity*)
        iOS
    * **SDK Version**
       pod 'GoogleMobileAdsMediationMoPub'
       pod "VungleSDK-iOS", "6.5.2"
       pod 'MoPub-Vungle-Adapters', '6.5.2.0'

**Comment by dravyan** [comment]
@dylancompanjen , can you help clarify whether you are trying to use MoPub mediation adapters or Google mediation adapters?. You are mediating from MoPub and also Google to MoPub?

Thanks,
Dravya Nataraj
MoPub Team

**Comment by dylancompanjen** [comment]
@dravyan So my main partner is AdMob and I integrated MoPub trough mediation. As I haven't seen good results with the marketplace only, I'm adding networks with their adapters.
