### ISSUE TITLE
Swift compiler error: Could not build Objective-C module 'MoPub_Mintegral_Adapters'

### ISSUE THREAD

**Issue by wdy-gogolook** [mopub/mopub-ios-mediation#266]
1. **What is the issue?**
 When I add "import MoPub_Mintegral_Adapters" to a swift file in my project, Xcode shows swift compiler error: `Could not build Objective-C module 'MoPub_Mintegral_Adapters`

`MintegralBannerCustomEvent.h`, `MintegralInterstitialCustomEvent.h`, and `MintegralRewardedVideoCustomEvent.h` have no proper `__has_include` preprocessor to handle the modulemap config of recent mopub-ios-sdk. They all need the following snippet to properly import `MoPub.h`

```
#elif __has_include(<MoPub/MoPub.h>)
    #import <MoPub/MoPub.h>
```
Note that I integrate MoPub_Mintegral_Adapters to my project through cocoapods

**Comment by chauduyphanvu** [comment]
@wdy-gogolook, thanks for letting us know! This has now been addressed in https://github.com/mopub/mopub-ios-mediation/commit/5fa47e7a62465b0262f7deb9de38966d7746b6f9. A CocoaPods release should finish in a few minutes. 

Let us know if you need anything else.

Vu Chau
MoPub Team

**Comment by wdy-gogolook** [comment]
@chauduyphanvu That's great! Much obliged!

Luis Wu
