### ISSUE TITLE
Valid Architectures for 32-bit iPhone Simulator using AdMob

### ISSUE THREAD

**Issue by d-date** [mopub/mopub-ios-mediation#274]
1. **What is the issue?**
    Since Google AdMob removed i386 architecture from v7.56.0, MoPub meditation also should follow this.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Platform** (*Android, iOS, Unity*)
        iOS
    * **MoPub SDK Version**
        5.12.0
    * **Mediation SDK Name & Version**
        AdMob
    * **Mediation Adapter Version**
        7.56.0
    * **Steps to reproduce the issue** (include integration steps if not standard)
        1. Update Google Mobile Ad SDK to v7.56.0 and later
        2. Build your project
    * **Observed behavior**
        <img width="359" alt="Screen Shot 2020-04-11 at 14 16 54" src="https://user-images.githubusercontent.com/20222809/79036042-1fe1f380-7bff-11ea-914b-8249452fa955.png">

    * **Expected behavior** (if known)
        No warning has occurred
    * **Evidence** (if available)
       https://developers.google.com/admob/ios/rel-notes
       > Removed i386 architecture. 32-bit simulator support no longer exists.

**Comment by chauduyphanvu** [comment]
@d-date, thanks for letting us know! We should be able to fix this early next week.

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
This was addressed in https://github.com/mopub/mopub-ios-mediation/commit/69c70a6d29226644563d5bcc2becec5a97a779ba.
