### ISSUE TITLE
Error compiling MoPub-AdMob v7.58.0

### ISSUE THREAD

**Issue by rob-keepsafe** [mopub/mopub-ios-mediation#277]
1. **What is the issue?**
    <img width="759" alt="Screen Shot 2020-04-23 at 2 55 57 PM" src="https://user-images.githubusercontent.com/30269720/80163667-8e657080-8572-11ea-8fe8-766088e960f6.png">

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Platform** (*Android, iOS, Unity*)
        iOS
    * **MoPub SDK Version**
        5.12.1
    * **Mediation Adapter Version**
        'MoPub-AdMob-Adapters', '~> 7.58.0'
    * **Device model and OS Version**
        Xcode 11.4, iOS 13.x
    * **Steps to reproduce the issue** (include integration steps if not standard)
        - Install MoPub version above
        - Install AdMob adapter via CocoaPods
        - Try to compile
    * **Observed behavior**
        Doesn't compile since valid architectures is incorrect and misses common architectures (in this case, arm64). See https://github.com/CocoaPods/Specs/blob/master/Specs/9/3/7/MoPub-AdMob-Adapters/7.58.0.0/MoPub-AdMob-Adapters.podspec.json#L23

        Also shouldn't include `x86_64` since that was supposed to have been closed via https://github.com/mopub/mopub-ios-mediation/issues/274

    * **Expected behavior** (if known)
        Should compile because it should have all valid iOS architectures in the podspec 

        Valid architectures:
        - arm64
        - arm64e
        - armv7
        - armv7s

    * **Evidence** (if available)
        
<img width="759" alt="Screen Shot 2020-04-23 at 2 55 57 PM" src="https://user-images.githubusercontent.com/30269720/80163667-8e657080-8572-11ea-8fe8-766088e960f6.png">

**Comment by rob-keepsafe** [comment]
Temporary workaround in your Podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # See https://github.com/mopub/mopub-ios-mediation/issues/277
      if %w[MoPub-AdMob-Adapters].include? target.to_s
        config.build_settings['VALID_ARCHS'] = ['arm64e arm64 armv7s armv7']
      end
    end
  end
end
```

**Comment by escamillar** [comment]
> Temporary workaround in your Podfile:
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       # See https://github.com/mopub/mopub-ios-mediation/issues/277
>       if %w[MoPub-AdMob-Adapters].include? target.to_s
>         config.build_settings['VALID_ARCHS'] = ['arm64e arm64 armv7s armv7']
>       end
>     end
>   end
> end
> ```

Maybe I'm missing something? Doesn't seem the architectures change at all and I'm also getting 

`rameworks.sh: line 144: ARCHS[@]: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code
`
When trying to build for a device, I can still compile for the emulator.

Haven't tried rolling back to a previous version of the adapters. Worth trying or is this an Xcode 114 issue?

**Comment by chauduyphanvu** [comment]
This is addressed in https://github.com/mopub/mopub-ios-mediation/commit/0ab8d4be5aee5dcf1d651b56116226dd4d46de7d ([podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/9/3/7/MoPub-AdMob-Adapters/7.58.0.1/MoPub-AdMob-Adapters.podspec.json#L23)). 

Let us know if you need anything else!
