### ISSUE TITLE
Mintegral doesn't notify Mopub if there are missing keys in the info dictionary of a native ad

### ISSUE THREAD

**Issue by RomainLofaso** [mopub/mopub-ios-mediation#293]
Hi,

There is a dead path that can be interesting to fix so that the Publishers get a quick feedback if they forget keys in the MoPub Dashboard.

In the following, the `errorMsg` is always nil:
https://github.com/mopub/mopub-ios-mediation/blob/a2df75214b803d26e563832c6bca86a815e0f752/Mintegral/MintegralNativeCustomEvent.m#L32-L43

Thanks,
Romain @ Criteo

**Comment by chauduyphanvu** [comment]
@RomainLofaso, thanks for letting us know! 

What you are seeing here is actually an expected behavior (it is working as we intended it to). On the MoPub dashboard, if one or more keys are empty for a particular mediation network, MoPub cannot bid. When you send an ad request to MoPub using an ad unit ID configured to mediate that network (Mintegral in this case), we don't have a complete set of info from Mintegral to work with.

As a result, since Mintegral does not bid, it cannot win the auction. Because of that, the MoPub ad server doesn't tell the SDK to call the adapters, which is where the code you are looking at sits. It's never called, and that's why publishers don't get notified.

Let me check with the rest of the team on what we can offer here as a means to validate data.

Vu Chau
MoPub Team

**Comment by RomainLofaso** [comment]
Hi Vu,

Thank you for your feedback. If I understood you well, I think that we are align with the expected behaviour: if there are empty or missing keys in the Dashboard, MoPub and Mintegral cannot bid because they haven't got a complete set of information. In that case, Mintegral should call the delegate for notifying an error.

The code that I linked in my previous comment handles the case where there are missing keys. The error management is not handled correctly: if there is a missing key, we do not notify the delegate that there is an error.

Here is a simple unit-test with the extracted piece of code for clarification. The assertion of the test fails:
```
#import <XCTest/XCTest.h>

@interface TestMoPubTests : XCTestCase

@end

@implementation TestMoPubTests

- (void)testContainsAllKeysWithMissingKey {
    NSDictionary *info = @{
        @"appId" : @"app id",
        //@"appKey": @"app key", MISSING KEY
        @"unitId": @"unit id",
        @"placementId": @"placement id"
    };
    
    BOOL containsAllKeys = [self containsAllKeysInInfo:info];
    
    XCTAssertFalse(containsAllKeys);
}


- (BOOL)containsAllKeysInInfo:(NSDictionary *)info
{
   NSString *appId = [info objectForKey:@"appId"];
    NSString *appKey = [info objectForKey:@"appKey"];
    NSString *unitId = [info objectForKey:@"unitId"];
    NSString *placementId = [info objectForKey:@"placementId"];
    
    NSString *errorMsg = nil;
    
    if (!appId) errorMsg = [errorMsg stringByAppendingString: @"Invalid or missing Mintegral appId. Failing ad request. Ensure the app ID is valid on the MoPub dashboard."];
    if (!appKey) errorMsg = [errorMsg stringByAppendingString: @"Invalid or missing Mintegral appKey. Failing ad request. Ensure the app key is valid on the MoPub dashboard."];
    if (!unitId) errorMsg = [errorMsg stringByAppendingString: @"Invalid or missing Mintegral unitId. Failing ad request. Ensure the unit ID is valid on the MoPub dashboard."];
    
    if (errorMsg) {
       // Here is the delegate call in the real implementation
       // [self.delegate nativeCustomEvent:self didFailToLoadAdWithError:MPNativeAdNSErrorForInvalidAdServerResponse(errorMsg)]; 
        return NO;
    }
    return YES;
}

@end
```

Concretely, we never enter in the condition `if (errorMsg)` so the delegate is never called for an error.

If my point of view is correct, the simplest way to fix it is by tweaking the declaration of `errorMsg`:
```
 NSString *errorMsg = @"";
```

Quick note: I don't use the Mintegral adapter. I have just catched this error while browsing the repository.

Romain

**Comment by chauduyphanvu** [comment]
@RomainLofaso, I agree that should be the expected outcome—to have the adapters validate user input and fail accordingly. What's happening here seems to be that the ad server is not returning the adapter class name to the SDK, so the adapter itself (including any validation code) isn't called at all (as opposed to a bug in the validation code). That results in a silent failure that you are seeing.

To be clear, this is not a Mintegral adapter (or any adapter issues). Let me check with the rest of the team on what we can do here. Thanks!
