### ISSUE TITLE
MoPub-AdMob-Adapters module uses UIWebView which make apps non-acceptable by AppStore

### ISSUE THREAD

**Issue by bohdanuhryn** [mopub/mopub-ios-mediation#296]
Hi,
I use mopub-ios-sdk and MoPub-AdMob-Adapters in my custom library for flutter. Last update of mopub (5.13.0 - issue [#313](https://github.com/mopub/mopub-ios-sdk/issues/313)) is good end does not contain [UIWebView](https://developer.apple.com/documentation/uikit/uiwebview) component which is deprecated and makes app non-acceptable by Apple Store.

But, last version of MoPub-AdMob-Adapters (7.60.0.0) still depends on UIWebView.

Output of command `grep -R "UIWebView" example/ios`:
```
Binary file example/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/GoogleMobileAds matches
```

My library module dependencies:
```
  s.dependency 'mopub-ios-sdk', '5.13.0'
  s.dependency 'MoPub-AdMob-Adapters', '7.60.0.0'
```

**Comment by chauduyphanvu** [comment]
@bohdanuhryn, the AdMob team addresses this concern in [this post](https://groups.google.com/d/msg/google-admob-ads-sdk/QuZMbjIyxn8/MSYok3ACBwAJ). Specifically, `grep -R "UIWebView"` doesn't indicate that an SDK is calling UIWebView APIs. 

Let us know if you have any questions.
Vu Chau
MoPub Team
