### ISSUE TITLE
Please update IronSource SDK to 6.18.0.1	

### ISSUE THREAD

**Issue by firehot** [mopub/mopub-ios-mediation#308]
IronSource SDK to 6.18 submitting to app store is triggered.
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by hmertkahraman** [comment]
Hi @firehot ,

The new version of ironSource adapters that certify the new ironSource SDK version 6.18.0.1 will be released very soon. You may monitor the update on [Mediation Integration Tool](https://developers.mopub.com/publishers/mediation/integrate/) and download to verify it fixes WebView issue accordingly.

Thanks,
MoPub Team

**Comment by hmertkahraman** [comment]
Hi @firehot ,

New ironSources adapters are [released](https://github.com/mopub/mopub-ios-mediation/releases/tag/ironsource-6.18.0.1.0). Could you please update to these ones and retry?

Thanks,
Mert

**Comment by firehot** [comment]
Thank you for your work, this update can be submitted to apple store review.
