### ISSUE TITLE
MoPub iOS build on failed using FacebookAudienceNetwork

### ISSUE THREAD

**Issue by psstevenchan** [mopub/mopub-ios-mediation#318]
Unity: 2019.4.5f1
Xcode version: 11.3
CocoaPods version: 1.9.3
MacOS Mojave: 10.14.6
Mopub version: 5.13.1

<iosPods>
   <iosPod name="MoPub-FacebookAudienceNetwork-Adapters" subspecs="['Network']" minTargetSdk="8.0" bitcodeEnabled="false" version="5.10.1.1" mopub-key="IOS_ADAPTER_VERSION"/>
 </iosPods>

ld: in /Users/builder/TestProjects/TestMopub5.13.1/Build/Pods/FBAudienceNetwork/Static/FBAudienceNetwork.framework/FBAudienceNetwork(FBANInterstitialAdAdapter.m.o), could not parse object file /Users/builder/TestProjects/TestMopub5.13.1/Build/Pods/FBAudienceNetwork/Static/FBAudienceNetwork.framework/FBAudienceNetwork(FBANInterstitialAdAdapter.m.o): 'Invalid bitcode version (Producer: '1103.0.32.59.0_0' Reader: '1100.0.33.16_0')', using libLTO version 'LLVM version 11.0.0, (clang-1100.0.33.16)' file '/Users/builder/TestProjects/TestMopub5.13.1/Build/Pods/FBAudienceNetwork/Static/FBAudienceNetwork.framework/FBAudienceNetwork' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chauduyphanvu** [comment]
@psstevenchan, which Facebook [adapter package](https://github.com/mopub/mopub-unity-mediation/tree/master/unity-packages) are you integrating? Could you also confirm how you integrate both MoPub and Facebook in your Unity project? 

Vu Chau
MoPub Team

**Comment by psstevenchan** [comment]
I use Facebook Audience Network 1.15.12, and install from the SDK Manager in UnityEditor

**Comment by psstevenchan** [comment]
I can build successfully if using xcode 11.6

**Comment by chauduyphanvu** [comment]
@psstevenchan, sounds good! Also, according to [Facebook's changelog](https://developers.facebook.com/docs/audience-network/changelog-ios/), starting from the v5.7.0 SDK release, bitcode is no longer supported. It looks like you might have had bitcode enabled in your Xcode project from the initial log messages.
