### ISSUE TITLE
[IronSource] Please update to v7 for iOS 14 support

### ISSUE THREAD

**Issue by iwasrobbed-ks** [mopub/mopub-ios-mediation#324]
The current mediation release for IronSource is v6.18.0, however iOS 14 support is only in v7+

Please let us know once this is able to be released / certified so we can finalize our iOS 14 testing 🙏 

Thank you!

See https://developers.ironsrc.com/ironsource-mobile/ios/ironsource-sdk7-update-guide/

**Comment by hmertkahraman** [comment]
Hi @iwasrobbed-ks ,

MoPub ironSource iOS adapters for v7+ are **just** released. You can integrate them to finalize your testing.

Thanks,
Mert
