### ISSUE TITLE
[AdMob] Adapter is broken for flexible sizing of banner ads

### ISSUE THREAD

**Issue by iwasrobbed-ks** [mopub/mopub-ios-mediation#335]
1. **What is the issue?**
    The `MPGoogleAdMobBannerCustomEvent` class rejects the flexible banner ad sizes (e.g. `kMPPresetMaxAdSize50Height`) as invalid so it fails to load any initial ads for the first 30 to 45 seconds until the ad refreshes enough to change the max ad size to the frame size

    The `adWidth <= 0` check here fails:

<img width="1085" alt="Screen Shot 2020-10-08 at 12 02 44 PM" src="https://user-images.githubusercontent.com/30269720/95485254-7a1a0200-095f-11eb-87d6-fd7be45c7cd7.png">

Dumping the info and size shows:

```
(lldb) po info 
{
    adHeight = 50;
    adUnitID = "<admob ad unit id here>";
    adWidth = 320;
}
(lldb) po size
(width = 0, height = 50)
```

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        Banner
    * **Platform** (*Android, iOS, Unity*)
        iOS
    * **MoPub SDK Version**
        5.14.1
    * **Mediation SDK Name & Version**
        'MoPub-AdMob-Adapters', '~> 7.65.0'
    * **Mediation Adapter Version**
        7.65.0.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        6c3098f38ee1427eba2a43881f931daa
    * **Device model and OS Version**
        iOS 14.0.1 (simulator or device)
    * **Steps to reproduce the issue** (include integration steps if not standard)
        1. Load banner ad w/ an AdMob unit 
        2. Check console logs and see errors below in observed behavior
        3. Wait for upwards of a minute and eventually the footer ad loads
    * **Observed behavior**
        The ad fails to load initially and it then waits 30-45 seconds to refresh again with a different ad size which is valid and can be shown. This means a lot of initial revenue is lost since most users might not stay on a given screen for that long.

        ```
        [MoPub][MPBannerAdManager] Banner ad view is fetching ad type: admob_native
        [MoPub][MPGoogleAdMobBannerCustomEvent] Adapter MPGoogleAdMobBannerCustomEvent failed to load ad: (17) Google AdMob banner failed to load due to invalid ad width and/or height.
        ```

    * **Expected behavior** (if known)
        When passing in a "flexible size", the ad loads immediately (this is currently only true if you pass in a custom size, e.g. a non-zero and non-negative number)

    * **Evidence** (if available)
        See above

**Comment by chauduyphanvu** [comment]
@iwasrobbed-ks, could you share some code that reproduces this behavior? I'm trying in the MoPub iOS sample app and the banner loads successfully on first tries:

![image](https://user-images.githubusercontent.com/25616035/95492614-5956aa00-0969-11eb-9610-29250384b6d1.png)

**Comment by iwasrobbed-ks** [comment]
@chauduyphanvu I believe that's because the `MPAdView` in your sample app has a frame before you ever load it. If you first load the ad and then add it to the view hierarchy after it successfully loads, this would trigger the bug since it doesn't have a frame originally (because you're telling it what max size it _should_ support when you load the ad, not what the ad view's current frame is).

A very simple way to repro is to change:

AdTableViewController.swift
```swift
// The ad view will be attached to the table header if available.
tableView.tableHeaderView = dataSource.adContainerView
```

to

```swift
tableView.tableHeaderView = nil
```

and then try to load the ad.

If you put a breakpoint in the `MPGoogleAdMobBannerCustomEvent.requestAdWithSize...` function like shown above, you'll see it hits that error every time.

**Comment by chauduyphanvu** [comment]
@iwasrobbed-ks, ah, that makes sense. It's an intended behavior. We expect you to set a frame before you make the ad request ([documented here](https://developers.mopub.com/publishers/ios/banner/#loading-banner-ads-in-your-app)). It's a requirement starting from v5.8.0 of the MoPub iOS SDK, so that's strange how you've only running into this problem now.

Could you confirm if setting a frame size works for you? Let us know if you need anything!

**Comment by iwasrobbed-ks** [comment]
Thank you @chauduyphanvu ! Historically there has been no guarantee that we'll fill the ad request so that's why we haven't been adding it to the view hierarchy until after we know it's successfully loaded (otherwise it'd be a big empty white space)

I think for now we'll just use the custom CGSize approach since it seems to support our implementation versus using the flexible sizes

Thanks again
