### ISSUE TITLE
Problem in `MoPub-FacebookAudienceNetwork-Adapters.podspec.json`

### ISSUE THREAD

**Issue by leberwurstsaft** [mopub/mopub-ios-mediation#338]
1. **What is the issue?**
    > Use of `user_target_xcconfig` in pod specs is discouraged and causes trouble

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. 
    * **Mediation Adapter Version**
        > MoPub-FacebookAudienceNetwork-Adapters 6.0.0 and up
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Install `MoPub-FacebookAudienceNetwork-Adapters` version 6.0.0+ using Cocoapods together with some other pod that also uses `user_target_xcconfig` in it's podspec to over write the `EXCLUDED_ARCHS` setting.
    * **Observed behavior**
        > Cocoapods emits warnings like this: `[!] Can't merge user_target_xcconfig for pod targets: [... list of pods ...]. Singular build setting EXCLUDED_ARCHS[sdk=<...>] has different values.`
    * **Expected behavior** (if known)
        > No warnings should be shown.
    * **Evidence** (if available)
        > The Cocoapods pod spec syntax reference discourages the use of this attribute: https://guides.cocoapods.org/syntax/podspec.html#user_target_xcconfig

**Comment by chauduyphanvu** [comment]
@leberwurstsaft, thanks for letting us know! We'll see what we can do here.

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
Closing as won't do (there was no sufficiently convincing argument).
