### ISSUE TITLE
Problems in 'MoPub-FacebookAudienceNetwork-Adapters', version: '6.0.0.1'

### ISSUE THREAD

**Issue by BigabilityLiu** [mopub/mopub-ios-mediation#342]
1. **What is the issue?**
After I click at Facebook native AD, it presents well, but do not response to `- (void)willPresentModalForNativeAd:(MPNativeAd *)nativeAd;` function in protocol `MPNativeAdDelegate`, and the statistical result `CTR` in mopub Dashboard do not change

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ x] I searched https://developers.mopub.com/ and found no answer.
    - [ x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
 Native Video
    * **Platform** (*Android, iOS, Unity*)
iOS
    * **MoPub SDK Version**
5.14.1
    * **Mediation SDK Name & Version**
FBAudienceNetwork & 6.0.0
    * **Mediation Adapter Version**
MoPub-FacebookAudienceNetwork-Adapters & 6.0.0.1
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
Any unit ID has Facebook Network Line item is ok.
    * **Device model and OS Version**
iPhone 11, iOS 13.6
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. CocoPods install 'mopub-ios-sdk', '5.14.1' and 'MoPub-FacebookAudienceNetwork-Adapters', '6.0.0.1'
        > 2. Add a UIView that implement to NativeMopubAdView protocol
        > 3. Initial a MPNativeAdRequest the has FacebookNativeAdRenderer configuration
        > 4. `MPNativeAdRequest` call `startWithCompletionHandler`, get a `MPNativeAd` and showing well
        > 5. Click at the AD view `cell to action` label, showing the Install page well, then close the Install page.
    * **Observed behavior**
        > `- (void)didDismissModalForNativeAd:(MPNativeAd *)nativeAd;` do response
        > `- (void)willPresentModalForNativeAd:(MPNativeAd *)nativeAd;` function in protocol `MPNativeAdDelegate` do not response
        >  the statistical result `Impressions` in mopub Dashboard increase, but `Clicks` and `CTR` do not increase
    * **Expected behavior** (if known)
        > Function `- (void)willPresentModalForNativeAd:(MPNativeAd *)nativeAd;` will call
        > `Clicks` and `CTR` data will increase
    * **Evidence** (if available)
        > None

**Comment by BigabilityLiu** [comment]
For now, I use the SDK Version below to solve the problem.

**Comment by p158276** [comment]
Hi @BigabilityLiu ,
Thanks for your information. 
We will check it internally and let you know if there's any feedback.

Yoyo Lin
MoPub Team

**Comment by chauduyphanvu** [comment]
@BigabilityLiu, this issue is no longer present in the more recent adapters. Could you upgrade to v6.2.0.0 and let us know if you continue seeing the issue?

Vu Chau
MoPub Team
