### ISSUE TITLE
Google-Mobile-Ads-SDK revert to version 7.39 with latest Crashlytics

### ISSUE THREAD

**Issue by SmartHbdev** [mopub/mopub-ios-mediation#343]
1. **What is the issue?**
Google-Mobile-Ads-SDK revert to version 7.39.0 if  'Firebase/Crashlytics'  is present in version 7.0.0

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ x] I searched https://developers.mopub.com/ and found no answer.
    - [x ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
       
    * **Platform** (*Android, iOS, Unity*)
IOS
    * **MoPub SDK Version**
5.14.1
    * **Mediation SDK Name & Version**
MoPub-AdMob-Adapters 
    * **Mediation Adapter Version**
        7.66.0
    * **Steps to reproduce the issue** (include integration steps if not standard)
Use pod 'Firebase/Crashlytics'  with MoPub-AdMob-Adapters 
    * **Observed behavior**
MoPub-AdMob-Adapters  revert to version 7.39.0 
    * **Expected behavior** (if known)
       MoPub-AdMob-Adapters  should stay over version 7.66.0.

To resolve the issue, Mopub must upgrade to Google-Mobile-Ads-SDK 7.67.1 which is compatible with latest Crashlytics 7.0.0

You can see more log here:
https://github.com/firebase/firebase-ios-sdk/issues/6878

**Comment by chauduyphanvu** [comment]
@SmartHbdev, thanks! We should have this done by the end of the week. I'll post an update here when so.

Vu Chau
MoPub Team,

**Comment by chauduyphanvu** [comment]
Should be resolved in https://github.com/mopub/mopub-ios-mediation/commit/b23e866c423942d2afc15606f294914d64714749. Let us know if you continue seeing the issue!
