### ISSUE TITLE
Mopub mediation - sometimes ads load but do not look correct

### ISSUE THREAD

**Issue by xta** [mopub/mopub-ios-mediation#352]
1. **What is the issue?**
    > When ad is loaded, I sometimes get a black rectangle instead of the ad.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [X] I searched https://developers.mopub.com/ and found no answer.
    - [X] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [X] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Banner
    * **Platform** (*Android, iOS, Unity*)
        > iOS
    * **MoPub SDK Version**
        > 5.15.0
    * **Mediation SDK Name & Version**
        > pod 'MoPub-AdMob-Adapters', '7.68.0.2'
    * **Mediation Adapter Version**
        > See above (Mediation SDK)
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Using my production 1.) mopub marketplace, 2.) admob
    * **Device model and OS Version**
        > iPhone XS, iOS v14.2
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Build my app and watch the ads run. Usually, I get a correct (production) ad. Sometimes I get a black rectangle. I have never tried to click on the ad, so I cannot tell if it responds to touch.
    * **Observed behavior**
        > It usually works, but sometimes it doesn't (intermittent issue)
    * **Expected behavior** (if known)
        > All the ads look like regular ads
    * **Evidence** (if available)
        > See screenshot. Note: top half is blurred out as it is not relevant. The ads show up at the bottom of the screen, where the black rectangle is. Usually the bottom (where black rectangle is) has a correct ad, but sometimes it shows like this. 
![screenshot](https://user-images.githubusercontent.com/465358/101340027-0e0b2b80-3834-11eb-8c01-aeb7c6c7c513.PNG)

The logs show:

```
[MoPub][MPBannerAdManager] Banner ad view is fetching ad type: mraid
[MoPub][MPBannerAdManager][e794f905321547ffa3798d6e0d2d4dd0] Ad loaded
 ad loaded. (width 320.000000, height 50.000000)
 
```

**Comment by xta** [comment]
Note: I am running mopub mediation with only Marketplace ads enabled and see this issue intermittently. I cannot tell if this is an issue with mopub mediation SDK or Marketplace ads.

**Comment by chauduyphanvu** [comment]
@xta, this seems to be a broken ad. How often are you seeing creatives like this? 

If you have an ad unit ID or the ad response (logged by the MoPub SDK to the console) when this issue happens, feel free to share it with us and we can debug further. Thanks!

Vu Chau
MoPub Team

**Comment by xta** [comment]
Thanks @chauduyphanvu You can close this issue. The issue happens intermittently.

It appears that this ID has shown up multiple times with issues: e794f905321547ffa3798d6e0d2d4dd0.

**Comment by chauduyphanvu** [comment]
@xta - thanks. 

Since we're only handling code-related issues on this tracker, in the future, when this issue happens again, feel free to file a support ticket with the ad responses, screenshots, and ad unit ID(s) and the team should be able to help you.
