### ISSUE TITLE
I'm having an issue with not being able to build the Vungle Mediation Adapter.

### ISSUE THREAD

**Issue by HyunjoonKo** [mopub/mopub-ios-mediation#355]
1. **What is the issue?**
    > Could not build Objective-C module 'MoPub_Vungle_Adapters'
    > I installed Vungle SDK, MoPub SDK, and mediations through CocoaPods.
    > There was no problem with other mediations, but there is a problem with the Vungle Adapter and the build does not work.
    > I cleaned up DerivedData and the build, but I still have problems.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Rewarded Video → Vungle mediation adapter.
    * **Platform** (*Android, iOS, Unity*)
        > iOS, Xcode Version 12.3 (12C33)
        > CocoaPods 1.10.0
        > Swift 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
    * **MoPub SDK Version**
        > 5.15.0
    * **Mediation SDK Name & Version**
        > Vungle SDK 6.8.1
    * **Mediation Adapter Version**
        > 6.8.1.3
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Provide the data here
    * **Device model and OS Version**
        > simulator (iPhone 12, iOS 14.3)
        > iPhone 12 Pro (iOS 14.3)
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. I just installed and built the library with CocoaPods.
    * **Observed behavior**
        > None.
    * **Expected behavior** (if known)
        > None.
    * **Evidence** (if available)
        > <img width="957" alt="dddd" src="https://user-images.githubusercontent.com/3861180/104712365-cc8c6b00-5765-11eb-98a0-1cfffadebfc4.png">
       >  <img width="966" alt="MoPub-Vungle-Adapters" src="https://user-images.githubusercontent.com/3861180/104712413-db731d80-5765-11eb-8e75-b40ea42f0c64.png">

       > - Include of non-modular header inside framework module 'MoPub_Vungle_Adapters.VungleRouter': '/Users/.../Pods/VungleSDK-iOS/VungleSDK.framework/Headers/VungleSDK.h'

       > - Include of non-modular header inside framework module 'MoPub_Vungle_Adapters.VungleRouter': '/Users/.../Pods/VungleSDK-iOS/VungleSDK.framework/Headers/VungleSDKNativeAds.h'

**Comment by hmertkahraman** [comment]
Hi @HyunjoonKo ,

Thanks for reaching out and providing the details.

Would you please be able to set the Allow Non-modular includes in Framework Modules in Build Settings for the affected target to YES and try with that? As described [here](https://stackoverflow.com/a/30697222/11984419) this should reveal the underlying issue which we can troubleshoot further. Please let us know of any new errors associated with this.

Thanks,
MoPub Team

**Comment by HyunjoonKo** [comment]
@hmertkahraman Thanks for suggesting a solution. But I still have the same problem with the build.

**Comment by hmertkahraman** [comment]
Hi @HyunjoonKo ,

Thanks for trying the suggestion. Would you be able to retry on a fresh clone of the pre MoPub installation version of your project: First installing MoPub and adapters from scratch via Cocoapods via `pod install` command. Then executing `pod repo update command` and verifying installation of the pods. Finally opening the XCWorkspace file (not the project) and building for the correct target.

If the issue persists after all this would you be able to share your podfile entries for MoPub adapters?

Thanks,
Mert

**Comment by HyunjoonKo** [comment]
@hmertkahraman 
My `Podfile`
```ruby
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

# warning: [Xcodeproj] Generated duplicate UUIDs
install! 'cocoapods', :deterministic_uuids => false

def extention_pods
  pod 'SwiftDate'
end

def require_pods
  pod 'Cartography'
  pod 'SwiftPullToRefresh', :git => 'https://github.com/HyunjoonKo/SwiftPullToRefresh.git', :branch => 'customized' # refresh control
  pod 'Mute'
  pod 'LNZCollectionLayouts', :git => 'https://github.com/assaulter/LNZCollectionLayouts.git' # collection view infinity scrolling
  pod 'ALTextInputBar', :git => 'https://github.com/hudl/ALTextInputBar.git' # community > write comments
  pod 'CircleProgressButton', :git => 'https://github.com/toshi0383/CircleProgressButton.git', :tag => '0.5.3' # download progress button
  pod 'JSONWebToken', :git => 'https://github.com/radianttap/JSONWebToken.swift.git' # SMR token
  pod 'BuzzAdBenefit', '2.0.6'
  pod 'SegementSlide'#, '3.0.0'
  pod "youtube-ios-player-helper", :git => 'https://github.com/HyunjoonKo/youtube-ios-player-helper.git' # modified safe area.
  mopub_pods
  extention_pods
end

def photos
  pod 'DKImagePickerController'#, :subspecs => ['PhotoEditor']
  # pod 'CropViewController' # library included in DKImagePickerController.
end

def twitter
  # pod 'TwitterKit', :git => 'https://github.com/HyunjoonKo/twitter-kit-ios.git', :branch => 'master'
  pod 'TwitterKit5' # https://github.com/touren/twitter-kit-ios
end

def mopub_pods
  pod 'mopub-ios-sdk', '~> 5.13'
  pod 'MoPub-AdMob-Adapters', '~> 7.69.0.1'
  pod 'MoPub-Vungle-Adapters', '~> 6.8.1.3'
  pod 'MoPub-Applovin-Adapters', '~> 6.14.11.0'
end

def google_pods
  pod 'Firebase', '7.2.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Crashlytics'
  pod 'GoogleSignIn'
  pod 'GoogleIDFASupport'
  pod 'google-cast-sdk' # Chromecast
  pod 'Firebase/AdMob' # AdMob with Firebase
  pod 'GoogleAds-IMA-iOS-SDK' # VAST pre-roll 
  pod 'GoogleMobileAdsMediationTestSuite', :configurations => ['Debug']
end

def amazon
  pod 'AWSS3'#, '~> 2.6.31'
end

def adpopcorn_pods
  pod 'AdPopcornOfferwall'
end

def tapjoy_pods
  pod 'TapjoySDK' # Tapjoy -> [Xcodeproj] Generated duplicate UUIDs
end

def applovin_pods
  pod 'AppLovinSDK'
end

def vungle_pods
  pod 'VungleSDK-iOS'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      config.build_settings['LD_NO_PIE'] = 'NO'
      if target.name == 'DKCamera' || target.name == 'DKPhotoGallery' || target.name == 'LNZCollectionLayouts' || target.name == 'DKImagePickerController'
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
  # warning removed: https://github.com/twitter-archive/twitter-kit-ios/issues/18
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.xcconfigs.each do |config_name, config_file|
      config_file.other_linker_flags[:frameworks].delete("TwitterCore")
      xcconfig_path = aggregate_target.xcconfig_path(config_name)
      config_file.save_as(xcconfig_path)
    end
  end
  # MoPub Vungle Adapter issue: https://github.com/mopub/mopub-ios-mediation/issues/355 but not working.
#  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
#      configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
#  end
end

# set target

target 'Mubeat' do
  require_pods
  google_pods
  photos
  amazon
  twitter
  tapjoy_pods
  adpopcorn_pods
  vungle_pods
  applovin_pods
end

target 'Mubeat share' do
  extention_pods
  amazon
end

target 'Mubeat DEV' do
  require_pods
  google_pods
  photos
  amazon
  twitter
  tapjoy_pods
  adpopcorn_pods
  vungle_pods
  applovin_pods
end

target 'Mubeat share DEV' do
  extention_pods
  amazon
end
```
I am converting my existing AdMob rewarded video to MoPub. (Keep other AdMob ads)
AdMob mediation adapters are directly inserted into the project and used, MoPub mediation adapters use CocoaPods.
As you can see, the other adapters are fine, but only the Vungle Adapter is causing problems. I reviewed the settings again and reinstalled CocoaPods(deleted Pods and `pod deintegrate`, `pod cache clean --all`, `pod install --repo-update`), but didn't fix the problem.

Looking at the [issue tracker of CocoaPods](https://www.google.com/search?q=swift+cocoapods+Include+of+non-modular+header+inside+framework+module+site:stackoverflow.com&client=safari&rls=en&sa=X&ved=2ahUKEwj0wL2Ti7buAhWTAYgKHa_WCbcQrQIoBHoECAYQBQ&biw=2247&bih=1293&dpr=2), this problem is expected to be difficult to fix, so I will install the manual.

**Comment by hmertkahraman** [comment]
Hi @HyunjoonKo ,

Many thanks for providing the information. Vungle adapter version you're using is v 6.8.1.3, and this is only dedicated towards MoPub 5.15 and above, as mentioned on it's podspec [here](https://github.com/CocoaPods/Specs/blob/master/Specs/e/4/4/MoPub-Vungle-Adapters/6.8.1.3/MoPub-Vungle-Adapters.podspec.json#L31). This might be indirectly leading to this issue. 

Would you be able to update your MoPub SDK to 5.15 and retry please?

Thanks,
Mert

**Comment by HyunjoonKo** [comment]
Hi @hmertkahraman 

As far as I know, the `~> x.y` symbol is an option to install the same or higher version than the minor version. So even if I type `~> 5.13`, version 5.15 is installed. 

Actually, it is not the cause of the problem because it was installed as follows. 
```
Installing MoPub-Vungle-Adapters (6.8.1.3)
Installing VungleSDK-iOS (6.8.1)
Installing mopub-ios-sdk (5.15.0)
```

**Comment by hmertkahraman** [comment]
Hi @HyunjoonKo ,

Thanks for verifying 5.15.0 is installed. We'll continue to try to help you out with your issue. Would you be able to ensure if the installed frameworks are publicly available for your desired target membership as [described in this suggestion](https://stackoverflow.com/a/43388154/11984419)?

Thanks,
Mert

**Comment by HyunjoonKo** [comment]
@hmertkahraman 
I am sorry for the late reply.

`Pods` → `VungleSDK-iOS` → `Frameworks` → Select `MoPub-Vungle-Adapters.framework` in Target Membership of `VungleSDK.framework`, it started to work.

Now that I have checked the operation, I will install and use the manual without CocoaPods until I modify the `podspec`. 
Please refer to [this link](https://stackoverflow.com/a/16037590/5649704) and modify it.

**Comment by dravyan** [comment]
@HyunjoonKo, thank you for sharing additional information. Since Vungle SDK is an objective-c framework, you need to create a bridging-header and import Vungle adapter filename to reference it in the Swift file. You do not need  `import MoPub_Vungle_Adapter`.
<img width="831" alt="Screen Shot 2021-02-17 at 2 24 47 PM" src="https://user-images.githubusercontent.com/44005959/108276040-0e754c00-712c-11eb-85cc-b7f98d98bfa1.png">
This should resolve the issue. Thanks.

**Comment by HyunjoonKo** [comment]
@dravyan 
Sorry for the late reply. The problem is solved.
