### ISSUE TITLE
UnityAds does not fire rewardedVideoAdShouldRewardForAdUnitID after clickthrough

### ISSUE THREAD

**Issue by nahdir** [mopub/mopub-ios-mediation#360]
1. **What is the issue?**
    UnityAds does not fire rewardedVideoAdShouldRewardForAdUnitID after clickthrough.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        Rewarded Video
    * **Platform** (*Android, iOS, Unity*)
        iOS
    * **MoPub SDK Version**
        5.15.0
    * **Mediation SDK Name & Version**
        Unity Ads 3.6.0
    * **Mediation Adapter Version**
        pod 'MoPub-UnityAds-Adapters', '3.6.0.0'
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        be581dbd07134b62aee24df74f0c2955
    * **Device model and OS Version**
        iPad 7th gen, iOS 14.3
    * **Steps to reproduce the issue** (include integration steps if not standard)
        1. Load mopub sample app.
        2. Load ad unit with Unity Ads as the only provider.
        3. Show ad.
        4. When prompted, click on the link to install Unity.
        5. Close store window & close the ad view.
        6. Observe rewardedVideoAdShouldRewardForAdUnitID is not triggered.
    * **Observed behavior**
        rewardedVideoAdShouldRewardForAdUnitID is not triggered.
    * **Expected behavior** (if known)
        rewardedVideoAdShouldRewardForAdUnitID is triggered, even after clickthrough.
    * **Evidence** (if available)
        
![Screen Shot 2021-02-02 at 16 18 56](https://user-images.githubusercontent.com/6412468/106631156-629cff80-6574-11eb-9b37-3639b033253f.png)

**Comment by dravyan** [comment]
Hi @nahdir, The `rewardedVideoAdShouldRewardForAdUnitID` is triggered only after the user completes watching the rewarded video and not on ad click. Once the video completes playing, you should be able to see the callback. Let us know if you still have any questions.

Thanks,
MoPub Team

**Comment by nahdir** [comment]
Hi @dravyan. If I click the small install button at the bottom right corner of the screen the video is dismissed and the `rewardedVideoAdShouldRewardForAdUnitID` is never triggered even though the ad has been interacted with and has completed playing.
![Screen Shot 2021-02-03 at 09 22 28](https://user-images.githubusercontent.com/6412468/106725945-cb7e8900-6601-11eb-8bf9-0fd9d48b702f.png)

**Comment by dravyan** [comment]
Hi @nahdir, thank you for sharing the above details. During clickthrough, the ad is still in the view controller and not completely dismissed/closed yet. UnityAds notify MoPub once the ad is finished playing and the close button is clicked to dismiss the ad i.e, [unityAdsDidFinish](https://github.com/mopub/mopub-ios-mediation/blob/fc927cb1d66c64f5d314687bcd5055d3a64014c8/UnityAds/UnityAdsRewardedVideoCustomEvent.m#L170-L174). Can you click on the close button on the top right corner once you go back to the ad after clickthrough?. That should fire reward callback too.

Thanks,
MoPub team

**Comment by nahdir** [comment]
Hi @dravyan. I understand that the callback would only be fired when the ad is dismissed/closed. I would not have been able to capture the screenshot with the callback missing if I had not closed it. Please find a video attached with the issue. Observe that the ad is clicked through and closed. There is still no callback.


https://user-images.githubusercontent.com/6412468/107012196-9f454280-6790-11eb-8b40-9e8fcfbc4145.mov

**Comment by dravyan** [comment]
@nahdir, Attaching the screen recording of our testing with the same the adunit. The callbacks seem to fire just fine. Could you please confirm you have registered for the delegate `rewardedVideoAdShouldRewardForAdUnitID` in your app?. Or can you share your project zip file where we can replicate the issue to help further?

https://user-images.githubusercontent.com/44005959/107099060-9327a800-67c5-11eb-99f4-0ae7be8f015d.mov

Thanks,
MoPub Team

**Comment by nahdir** [comment]
@dravyan Thanks for the video response. Your test case is not quite the same as I press the "Install Now" button at 11 seconds. After this the reward does not trigger. As you can see I am using the mopub test app so I am not the registering for the delegate callbacks.

**Comment by dravyan** [comment]
@nahdir, I was able to reproduce the issue the behavior you were seeing. Since the video is not watched completely and is clicked prior to that, UnityAds will not set the ad state to `kUnityAdsFinishStateCompleted` as shown [here](https://github.com/mopub/mopub-ios-mediation/blob/49f57e4f5e6b55b95fc27cbbe96db77e5ab3f919/UnityAds/UnityAdsRewardedVideoCustomEvent.m#L173-L176). This is the state that indicates the ad was played entirely by UnityAds. So the `rewardedVideoAdShouldRewardForAdUnitID` is not fired in such scenario.

Thanks,
MoPub tTam

**Comment by nahdir** [comment]
@dravyan Can you confirm this is a bug? At the moment even if a user interacts with the ad they do not get rewarded.

**Comment by dravyan** [comment]
Hi @nahdir, we are working with the UnityAds network on this and update once we have more information to share. Thanks.

**Comment by dravyan** [comment]
@nahdir, we have received a confirmation from Unity Ads that the behavior is expected if you have set up a skippable interstitial ad on Unity's dashboard instead of a nonskippable rewarded video. You can also reach out to unityads-support@unity3d.com if you have additional questions.
