### ISSUE TITLE
Mediation Adapters manual integration options

### ISSUE THREAD

**Issue by pieomy** [mopub/mopub-ios-mediation#363]
1. **What is the issue?**
    MoPub SDK have manual integration options as Framework.zip but mediation adapters only have source codes there is no .zip for adapters, How can use adapters as Adobe Air or Cordova developer? (I can not use pod, I need Dynamic or Static SDKs to add my project). Thanks

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        Rewarded Video
    * **Platform** (*Android, iOS, Unity*)
        iOS
    * **MoPub SDK Version**
        5.15.0
    * **Mediation SDK Name & Version**
        All
    * **Mediation Adapter Version**
        All
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        None
    * **Device model and OS Version**
        None
    * **Steps to reproduce the issue** (include integration steps if not standard)
        None
        None
    * **Observed behavior**
        None
    * **Expected behavior** (if known)
        None
    * **Evidence** (if available)
        None

**Comment by chauduyphanvu** [comment]
@pieomy, thanks for your interest in integrating MoPub on additional platforms. At this time, we do not offer mediation solutions for the platforms you mention. 

Let us know if there are any questions.

Vu Chau
MoPub Team
