### ISSUE TITLE
Please use __typeof instead of typeof

### ISSUE THREAD

**Issue by firatagdas** [mopub/mopub-ios-mediation#364]
When we use Chartboost adapter as following it immediately fails the build with syntax error. That is because Unity doesn't enable GNUXX on Xcode project. So we don't want to play with it as it is not recommended. We had to maintain this like 3 years. But there is simple solution.

You can change it with __typeof instead of typeof. Unity needs configuration as CXX and typeof is only available on GNUXX. According to stackoverflow, __typeof is enabled in both situation.

https://github.com/mopub/mopub-ios-mediation/blob/c1260ceef154351213c59bb838771fd58cb46913/Chartboost/ChartboostBannerCustomEvent.m#L31

https://github.com/mopub/mopub-ios-mediation/blob/master/Chartboost/ChartboostInterstitialCustomEvent.m#L48

https://github.com/mopub/mopub-ios-mediation/blob/master/Chartboost/ChartboostRewardedVideoCustomEvent.m#L48

**Comment by hmertkahraman** [comment]
Hello @firatagdas ,

We've gone ahead and [released the changes](https://github.com/mopub/mopub-ios-mediation/commit/bf1847182e03ef33d1f027ba9fa1eb75e60e64fb) on Chartboost iOS adapters with the new version: 8.4.0.1. Respective Unitypackage will be released during today.

Thanks,
MoPub Team
