### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by IgorRosocha** [mopub/mopub-ios-mediation#365]
Just wondering, if you guys have been thinking about SPM support? On our projects, `AdMob` adapter is currently the only dependency we need to link using Cocoapods.

**Comment by chauduyphanvu** [comment]
@IgorRosocha, thanks for getting in touch about SPM. We currently do not have plans for adapter distribution via SPM yet. I'll relay your feedback to the rest of the team and keep this thread updated if the plan changes.

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
Closing this issue as there are still no plans for SPM.
