### ISSUE TITLE
Snapchat adapter SnapAdIntersititalCustomEvent auto-property synthesis warnings

### ISSUE THREAD

**Issue by awojnowski** [mopub/mopub-ios-mediation#371]
Two warnings are given at build-time within the `SnapAdIntersititalCustomEvent` implementation file.

    Auto property synthesis will not synthesize property 'delegate' declared in protocol 'MPFullscreenAdAdapter'
    Auto property synthesis will not synthesize property 'localExtras' declared in protocol 'MPFullscreenAdAdapter'

Should add the following to the implementation to suppress the warnings:

```
@dynamic delegate;
@dynamic localExtras;
```

**Comment by dravyan** [comment]
Thank you for your report. We will look into this and update here.

Thanks,
MoPub Team

**Comment by awojnowski** [comment]
@dravyan Any update here? 1.1.1.0 still does not address this issue and requires updates from developer to suppress the warnings. My concern is that some developers may naturally synthesize these properties instead of acknowledging them as dynamic, thus introducing a bug.

**Comment by dravyan** [comment]
@awojnowski, this has been addressed in the latest Snap adapters release [v1.1.1.1](https://github.com/mopub/mopub-ios-mediation/commit/87146e9f40c5fb342b78a2b5f14b3a2015764377).
