### ISSUE TITLE
SnapAdInterstitialCustomEvent accesses -[UIApplication statusBarOrientation] from a thread other than the main thread

### ISSUE THREAD

**Issue by awojnowski** [mopub/mopub-ios-mediation#372]
This appears to occur reliably when trying to load an interstitial advertisement without having first initialized the SDK. Once the completion block fires, it will not be on the main thread which causes this issue to appear.

There is no adverse effect at this point in time, but there possibly could be in future versions of iOS.

Could possibly be an issue with the banner adapter as well, although I have not tested.

<img width="1642" alt="Screen Shot 2021-03-01 at 6 26 00 PM" src="https://user-images.githubusercontent.com/815376/109577731-b2abab00-7abb-11eb-9b95-4042044ceedc.png">

**Comment by dravyan** [comment]
Thank you for your report. We will look into this and update here.

-MoPub Team
