### ISSUE TITLE
Google-Mobile-Ads-SDK 7.68.0 and xcframework don't display Class name in storyboard

### ISSUE THREAD

**Issue by SmartHbdev** [mopub/mopub-ios-mediation#373]
1. **What is the issue?**
Google-Mobile-Ads-SDK class don't appear in the drop down menu to select the class name.
Adding the Class name manually don't load it as expected.
For example GADUnifiedNativeAdView don't load the outlets and we can't connect them to the views.

Google-Mobile-Ads-SDK 7.68.0 use xcframework, that's probably the issue

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
       Every format you can use on a UIView on a storyboard
    * **Platform** (*Android, iOS, Unity*)
        iOS
    * **MoPub SDK Version**
       Every version who use Google-Mobile-Ads-SDK 7.68.0
       Google-Mobile-Ads-SDK 7.67.0 is fine 
    * **Mediation SDK Name & Version**
        Google-Mobile-Ads-SDK
    * **Mediation Adapter Version**
        7.68.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        any
    * **Device model and OS Version**
        any
    * **Steps to reproduce the issue** (include integration steps if not standard)
        1. install version Google-Mobile-Ads-SDK 7.68.0 or Google-Mobile-Ads-SDK 7.69.0
        2. Go on the storyboard, select a UIView and try to select GAD* class. They are not listed
    * **Observed behavior**
        Probably a issue with xcframework migration
    * **Expected behavior** (if known)
        Admob class should be listed
    * **Evidence** (if available)

Not sure if it's a Cocoapod problem or a Admob issue and i agree that Mopub is probably not faulty but maybe it can save some time to other dev to know this issue.

Google-Mobile-Ads-SDK 8 is out and they use regular framework for the moment so no issue. Have you any range of time on when a it will be available in order to get latest versions of every dependency ?

**Comment by SmartHbdev** [comment]
If i try:
`pod 'Google-Mobile-Ads-SDK', '<7.68.0`
or
`pod 'MoPub-AdMob-Adapters', '<7.68.0'`

It Install me Installing `MoPub-AdMob-Adapters (7.39.0.0)`

The solution is:
`pod 'MoPub-AdMob-Adapters', '7.66.0.1'`

This way it install `Google-Mobile-Ads-SDK (7.66.0)`
If it can help other dev...

**Comment by chauduyphanvu** [comment]
>Google-Mobile-Ads-SDK 8 is out and they use regular framework for the moment so no issue. Have you any range of time on when a it will be available in order to get latest versions of every dependency ?

We are looking at next week or so. The new SDK is getting certified with the adapters as we speak. Stay tuned!

**Comment by chauduyphanvu** [comment]
Done in https://github.com/mopub/mopub-ios-mediation/commit/0744c5a3e0756ff0d5bdf97abf5976e4debc9984. Thanks!
