### ISSUE TITLE
Comment conflicts

### ISSUE THREAD

**Issue by casolorz** [mopub/mopub-ios-mediation#376]
On this file https://github.com/mopub/mopub-ios-mediation/blob/05f8335e54915678c3038a728711e83ddb9abd55/AdMob/MPGoogleAdMobInterstitialCustomEvent.m

There is this comment:

```
 // Consent collected from the MoPub’s consent dialogue should not be used to set up Google's
    // personalization preference. Publishers should work with Google to be GDPR-compliant.
```   

And on this file https://github.com/mopub/mopub-ios-mediation/blob/ca06d88b035be9748ef5b75463b2ac11010b3577/AdMob/GoogleAdMobAdapterConfiguration.m

There is this comment:

`// MoPub collects GDPR consent on behalf of Google`

They feel contradictory to me, which is it, is MoPub collecting GDPR consent for Google or not?

**Comment by chauduyphanvu** [comment]
@casolorz, thanks for pointing that out. I've removed the oudated comment in https://github.com/mopub/mopub-ios-mediation/commit/49d39fc4d3309bbe5d08220ee14f92294e306ed7.

Vu Chau
MoPub Team
