### ISSUE TITLE
Any ETA on AdMob 8.x support?

### ISSUE THREAD

**Issue by sgabello** [mopub/mopub-ios-mediation#378]

**Comment by chauduyphanvu** [comment]
@sgabello, we currently don't have an ETA yet. You can track progress on https://github.com/mopub/mopub-ios-mediation/pull/366. Thanks!

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
Done in https://github.com/mopub/mopub-ios-mediation/commit/0744c5a3e0756ff0d5bdf97abf5976e4debc9984. Thanks!
