### ISSUE TITLE
Admob 8.3.0.x not refreshing banners correctly

### ISSUE THREAD

**Issue by rbiddulph** [mopub/mopub-ios-mediation#383]
1. **What is the issue?**
   Admob mediation 8.3.0.x does not show more than one banner ad due to _MPGoogleAdMobBannerCustomEvent_ issue

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x ] I searched https://developers.mopub.com/ and found no answer.
    - [x ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        Banner
    * **Platform** (*Android, iOS, Unity*)
        iOS
    * **MoPub SDK Version**
        Latest
    * **Mediation SDK Name & Version**
        Google 8.3.0
    * **Mediation Adapter Version**
        admob 8.3.0.x
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        N/A
    * **Device model and OS Version**
        all iOS devices
    * **Steps to reproduce the issue** (include integration steps if not standard)
       implement admob banner mediation
    * **Observed behavior**
        banners will load an admob ad and then never refresh again
    * **Expected behavior** (if known)
        banners continue refreshing at desired rate
    * **Evidence** (if available)
       It appears that the root of the issue is the function _adViewDidRecordImpression_ being present in the mediation library _MPGoogleAdMobBannerCustomEvent_ class for callback when a banner ad is shown, whereas in google's documentation the callback is defined as _bannerViewDidRecordImpression_, and so the impression is never being recorded by mopub. SDK documentation available here: https://developers.google.com/ad-manager/mobile-ads-sdk/ios/api/reference/Protocols/GADBannerViewDelegate

**Comment by chauduyphanvu** [comment]
@rbiddulph, thanks for the report. This issue will be addressed today!

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
Fixed in https://github.com/mopub/mopub-ios-mediation/commit/9de08828c1e057ebf689c673b4ed76efab1317f7. Thanks!
