### ISSUE TITLE
New version for MoPub-Applovin-Adapters required

### ISSUE THREAD

**Issue by nhatduong** [mopub/mopub-ios-mediation#385]
hello, 
AppLovin has released a new SDK 10.2.0,  support iOS 14.5 ATT.  And, MoPub-Applovin-Adapters support ApplovinSDK 10.1.1.

Cocoapods constraints won't let us update. Please publish a new version MoPub-Applovin-Adapters support ApplovinSDK 10.2.0

Thank you,

**Comment by p158276** [comment]
Hi @nhatduong ,
Thanks for reaching out. AppLovin 10.2.0.0 has been certified and released. (https://github.com/mopub/mopub-ios-mediation/releases/tag/applovin-10.2.0.0) Let us know if you have any other questions.

Yoyo Lin
MoPub Team

**Comment by nhatduong** [comment]
@p158276 Thank you!
