### ISSUE TITLE
Mopub-Verizon-Adapters returns a 403 when using cocoa pods. 

### ISSUE THREAD

**Issue by ManueGE** [mopub/mopub-ios-mediation#389]
1. **What is the issue?**

    Can't install Verizon adapter using cocoa pods, it returns this error:

```
[!] Error installing Verizon-Ads-Core
[!] /usr/bin/curl -f -L -o /var/folders/7q/g6r1pt0x7fg1wzvdf9pd6jlh0000gn/T/d20210503-12644-1dqc44q/file.zip https://yahoo.bintray.com/maven/com/verizon/ads/ios-vas-core-cocoapods-artifact/2.4.0/ios-vas-core-cocoapods-artifact-2.4.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
```

This is my podfile:

```
target 'testvas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testvas
  pod 'MoPub-Verizon-Adapters'

end
```

II assume this is because the [Bintray sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). Verizon already released an SDK that fixes the issue (`2.6.0`) but you are still using an older version (`2.4.0`). 

Is there a workaround? What is the estimated time for a solution? 

Thanks.

**Comment by ManueGE** [comment]
Now it works, but it has been working intermittently the last week. I would like to have a permanent solution, so I'll stay tuned for your update. 

Thanks!

**Comment by chauduyphanvu** [comment]
@ManueGE, thanks for the confirmation. There have been a few [scheduled brownout sessions](https://status.bintray.com/) so what you experienced might be due to that.

**Comment by chauduyphanvu** [comment]
This should have been addressed in 1.13.0.0 (https://github.com/mopub/mopub-ios-mediation/commit/2416c11f96370f0e2860a4b909224afc5401144b). Check it out and let us know if you continue seeing the issue.

**Comment by mw-mmiller** [comment]
@chauduyphanvu My team is currently experiencing this issue

> [!] Error installing Verizon-Ads-Core
> [!] /usr/bin/curl -f -L -o /opt/buildAgent/temp/buildTmp/d20210719-9542-rz7l8g/file.zip https://yahoo.bintray.com/maven/com/verizon/ads/ios-vas-core-cocoapods-artifact/2.4.0/ios-vas-core-cocoapods-artifact-2.4.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'
> 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
>   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
>   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
> curl: (22) The requested URL returned error: 403 Forbidden

It appears the entire yahoo bintray subdomain is down.
> curl -fL https://yahoo.bintray.com/
> curl: (22) The requested URL returned error: 403 Forbidden

And bintray isn't reporting any issues
https://status.bintray.com/

Do you have any recommendations to alleviate the issue?

**Comment by chauduyphanvu** [comment]
@mw-mmiller, could you confirm which version of the Verizon adapters the team is trying to integrate? I've just checked the latest version (1.13.0.0) and everything was working well:

```
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing MoPub-Verizon-Adapters (1.13.0.0)
Installing Verizon-Ads-Core (2.7.0)
Installing Verizon-Ads-InlinePlacement (1.7.0)
Installing Verizon-Ads-InlineWebAdapter (1.7.0)
Installing Verizon-Ads-InterstitialPlacement (1.7.0)
Installing Verizon-Ads-InterstitialVASTAdapter (1.7.0)
Installing Verizon-Ads-InterstitialWebAdapter (1.7.0)
Installing Verizon-Ads-NativePlacement (1.13.0)
Installing Verizon-Ads-NativeVerizonNativeAdapter (2.8.0)
Installing Verizon-Ads-OMSDK (1.9.0)
Installing Verizon-Ads-StandardEdition (1.13.0)
Installing Verizon-Ads-Support (1.14.0)
Installing Verizon-Ads-URIExperience (2.8.0)
Installing Verizon-Ads-VASTController (1.9.0)
Installing Verizon-Ads-VerizonNativeController (2.14.0)
Installing Verizon-Ads-VideoPlayer (1.8.0)
Installing Verizon-Ads-WebController (1.6.0)
Installing Verizon-Ads-WebView (1.9.0)

Generating Pods project
Integrating client project
Pod installation complete! There are 3 dependencies from the Podfile and 20 total pods installed.
```

**Comment by mw-mmiller** [comment]
@chauduyphanvu thanks for the reply! We're using 1.9.0.1. I did some more digging and think I found the problem.

The MoPub-Verizon-Adapter versions 1.9.0.* reference Verizon-Ads-StandardEdition 1.9.0. The [spec for 1.9.0](https://github.com/CocoaPods/Specs/blob/master/Specs/0/0/9/Verizon-Ads-StandardEdition/1.9.0/Verizon-Ads-StandardEdition.podspec.json) has a bad source (yahoo.bintray.com). Verizon-Ads-StandardEdition 1.9.1 and [1.12+ specs](https://github.com/CocoaPods/Specs/blob/master/Specs/0/0/9/Verizon-Ads-StandardEdition/1.12.0/Verizon-Ads-StandardEdition.podspec.json) have a good source (artifactory.verizonmedia.com)

The MoPub-Verizon-Adapter version 1.13.0.0 reference Verizon-Ads-StandardEdition 1.13.0 which makes the cocoapods install happy.


I'll talk to my team to look into updating to 1.13.0.0. It could be an easier sell if there was a new version of MoPub-Verizon-Adapters like 1.9.1 that only updated the Verizon-Ads-StandardEdition to [1.9.1](https://github.com/CocoaPods/Specs/blob/master/Specs/0/0/9/Verizon-Ads-StandardEdition/1.9.1/Verizon-Ads-StandardEdition.podspec.json). Let me know what you think and thank you again for the help!

**Comment by chauduyphanvu** [comment]
Thanks for the confirmation! The reason the older versions no longer work is, like you said, of the Bintray deprecation. Verizon recently migrated to Maven/Artifactory, hence the newer versions are serving.

We don't normally retroactively make changes to historical adapter releases, but if this causes a big problem for you we can re-evaluate.

**Comment by mw-mmiller** [comment]
Thanks for the offer. We were able to workaround the issue by populating our Pod caches locally with the old version of the Verizon SDKs so there won't be a need to consider making a historical change.

I appreciate the help on this issue!
