### ISSUE TITLE
Google Mobile Ads Mediation

### ISSUE THREAD

**Issue by leearmstrong** [mopub/mopub-ios-mediation#39]
It seems with the GDPR consent handling we will have to handle consent and signalling to Google ourselves as they are not a supported network (along with Facebook).

This is done with Google by [adding the following](https://developers.google.com/admob/ios/eu-consent#forward_consent_to_the_google_mobile_ads_sdk) to a Google ad request...

```
GADRequest *request = [GADRequest request];
GADExtras *extras = [[GADExtras alloc] init];
extras.additionalParameters = @{@"npa": @"1"};
[request registerAdNetworkExtras:extras];
```

I cannot see how you would add this `GADExtras` to a request that has come via the mediation adapter.

If this is not possible then it is not possible to use Google Mobile Ads mediation via MoPub!

**Comment by rsatrasala** [comment]
@leearmstrong We are looking into this internally. We will put out a PR and release documentation early next week.

**Comment by chauduyphanvu1** [comment]
Confirming that this is supported in the newly-updated adapters: https://github.com/mopub/mopub-ios-mediation/commit/114b49efe409b5fc52ddb1e652fd5c3b22b8a2dd. Instructions for publishers will be published shortly.
