### ISSUE TITLE
New version for MoPub-AdColony-Adapters required

### ISSUE THREAD

**Issue by nhatduong** [mopub/mopub-ios-mediation#390]
hello,
AdColony has released a new SDK 4.6.1. And, MoPub-AdColony-Adapters support AdColonySDK 4.6.0.

Cocoapods constraints won't let us update. Please publish a new version MoPub-AdColony-Adapters support AdColonySDK 4.6.1

Thank you,

**Comment by chauduyphanvu** [comment]
@nhatduong, thanks for the news. 

We keep track of all new releases and run tests before we can approve and release new adapters. Typically, it takes 1 week on average. Thanks for your patience.

Vu Chau
MoPub Team

**Comment by dravyan** [comment]
@nhatduong, AdColony adapters [v4.6.1.0](https://developers.mopub.com/publishers/mediation/integrate/) is now available.
