### ISSUE TITLE
ERROR: Cannot find 'VungleAdapterConfiguration' in scope

### ISSUE THREAD

**Issue by fulldiver-ilya** [mopub/mopub-ios-mediation#391]
1. **What is the issue?**
    Unable to import `MoPub-Vungle-Adapters` as `podspec.dependency` for my own swift framework

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Platform** (*Android, iOS, Unity*)
        iOS 14.5
    * **MoPub SDK Version**
        5.16.2
    * **Mediation SDK Name & Version**
        MoPub-Vungle-Adapters
    * **Mediation Adapter Version**
        6.9.2.0
    * **Device model and OS Version**
        iOS Simulator x86_64
    * **Steps to reproduce the issue** (include integration steps if not standard)
        [example project](https://github.com/fulldiver-ilya/TestAdvertisement)
        just clone and make `pod install` inside root folder, then compile workspace as normal
    * **Observed behavior**
        Compilation failed with `Cannot find 'VungleAdapterConfiguration' in scope`
        The same issue with `MoPub_Chartboost_Adapters` -> `Cannot find 'ChartboostAdapterConfiguration' in scope` 
    * **Expected behavior** (if known)
        Workspace should be compiled successfully
    * **Evidence** (if available)
        https://github.com/fulldiver-ilya/TestAdvertisement

**Comment by dravyan** [comment]
@fulldiver-ilya ,
You need to add [bridging-header](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift) class in Swift as VungleSDK is obj-c framework. Create the header-bridging file and add the import statement `#import "VungleAdapterConfiguration.h"`. That should allow you to reference `VungleAdapterConfiguration`.

Thanks,
MoPub Team

**Comment by fulldiver-ilya** [comment]
Thank you @dravyan for the answer!
It's really true, when we talk about app that depends on ObjC framework, but in my case ObjC framework used inside my own Swift framework. For frameworks there is umbrella header file (cococapods generates it automatically and adds any .h files from sources), but how should I declare it?

I have a `.podspec` file that include .h files from my framework.
```
  spec.source_files = "MediationFramework/**/*.{swift,h}"
```
But I could not `#import "VungleAdapterConfiguration.h"` into `MediationFramework.h` because of `Could not build module 'MoPub_Vungle_Adapters'` error

And I don't know how to deal with it, do you have any suggestions?

**Comment by dravyan** [comment]
@fulldiver-ilya, are you still having issues here? Could you share your project zip so we can try to replicate it?

**Comment by dravyan** [comment]
@fulldiver-ilya, have you tried the solution #2 from [here](https://gist.github.com/bgromov/f4327343ad67a5f7216262ccbe99c376)?
