### ISSUE TITLE
Audience Network bidding

### ISSUE THREAD

**Issue by Jebastin500** [mopub/mopub-ios-mediation#397]
Hai Guys ,
I have created a whatsapp sticker Application by hiring someone . 
Now Audience Network showing move your apps to bidding. 
Im using audience network only no mediation. 
 What i need to do ? 
Please solve my problem ? 
The hired person not helping now 😐

Thanks in advance 🙂

**Comment by chauduyphanvu** [comment]
@Jebastin500, are you using Facebook Audience Network via MoPub's mediation? If not, you will need to speak with Facebook about how to migrate your account to bidding only.

This guide from Facebook might contain additional information: https://www.facebook.com/audiencenetwork/move-to-bidding.

Vu Chau
MoPub Team
