### ISSUE TITLE
AdMob mediation impact keyboard bring up

### ISSUE THREAD

**Issue by chenxi141017** [mopub/mopub-ios-mediation#403]
1. **What is the issue?**
    >  `GoogleAdMobAdapterConfiguration.m` -> `initializeNetworkWithConfiguration:complete:` -> `startWithCompletionHandler:` impact keyboard bring up

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ ] I searched https://developers.mopub.com/ and found no answer.
    - [ ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Rewarded Video
    * **Platform** (*Android, iOS, Unity*)
        > iOS (Use iOS SDK in Unity project, Unity version 2018.4.14f1)
    * **MoPub SDK Version**
        > 5.16.2
    * **Mediation SDK Name & Version**
        > Admob 8.4.0
    * **Mediation Adapter Version**
        > 8.4.0.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Any Ad Unit ID can reproduce the issue
    * **Device model and OS Version**
        > iPhone 6s (iOS 14.1) affected keyboard bring up
        > iPhoneX (iOS 14.0) not affected
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Init MoPub SDK in main thread after `didFinishLaunching` the game
        > 2. Click input view (Unity project created)
    * **Observed behavior**
        > Method `GoogleAdMobAdapterConfiguration.m` -> `initializeNetworkWithConfiguration:complete:`  was called not in main thread (so many thread was created). 
        > Method `GoogleAdMobAdapterConfiguration.m` -> `initializeNetworkWithConfiguration:complete:` ->  `startWithCompletionHandler:`,  will cause method `keyboardWillShow:` In Xcode project `Class/UI/Keyboard.mm` not invoke
    * **Expected behavior** (if known)
        > Keyboard bring up correctly
    * **Evidence** (if available)
        > Attach logs (device/network), mini debug builds (source code preferably), stack traces, screenshots / screen recordings, etc.
4. **My temporary solution**
 *  when invoke `initializeNetworkWithConfiguration:complete:` in `GoogleAdMobAdapterConfiguration.m` I invoke the callback immediately without call `startWithCompletionHandler:` method.
     
```
- (void)initializeNetworkWithConfiguration:(NSDictionary<NSString *, id> *)configuration
                                  complete:(void(^)(NSError *))complete {
    dispatch_async(dispatch_get_main_queue(), ^{
        if (complete != nil) {
          complete(nil);
        }
    });
}
```

* I noticed when request reward video adaptor will invoke `startWithCompletionHandler:` first in `MPGoogleAdMobRewardedVideoCustomEvent.m` -> `requestAdWithAdapterInfo:adMarkup:` . So I think my solution will not affect the MoPub SDK's workflow
```
- (void)requestAdWithAdapterInfo:(NSDictionary *)info adMarkup:(NSString *)adMarkup {
    [self initializeSdkWithParameters:info];
    
    // Cache the network initialization parameters
    [GoogleAdMobAdapterConfiguration updateInitializationParameters:info];
    
    self.admobAdUnitId = [info objectForKey:@"adunit"];
    if (self.admobAdUnitId == nil) {
        NSError *error =
        [NSError errorWithDomain:MoPubRewardedAdsSDKDomain
                            code:MPRewardedAdErrorInvalidAdUnitID
                        userInfo:@{NSLocalizedDescriptionKey : @"Ad Unit ID cannot be nil."}];
        
        MPLogAdEvent([MPLogEvent adLoadFailedForAdapter:NSStringFromClass(self.class) error:error], [self getAdNetworkId]);
        [self.delegate fullscreenAdAdapter:self didFailToLoadAdWithError:error];
        return;
    }
    
    GADRequest *request = [GADRequest request];
    if ([self.localExtras objectForKey:@"testDevices"]) {
      GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = self.localExtras[@"testDevices"];
    }

    if ([self.localExtras objectForKey:@"tagForChildDirectedTreatment"]) {
      [GADMobileAds.sharedInstance.requestConfiguration tagForChildDirectedTreatment:self.localExtras[@"tagForChildDirectedTreatment"]];
    }

    if ([self.localExtras objectForKey:@"tagForUnderAgeOfConsent"]) {
      [GADMobileAds.sharedInstance.requestConfiguration
          tagForUnderAgeOfConsent:self.localExtras[@"tagForUnderAgeOfConsent"]];
    }

    request.requestAgent = @"MoPub";

    if ([self.localExtras objectForKey:@"contentUrl"] != nil) {
        NSString *contentUrl = [self.localExtras objectForKey:@"contentUrl"];
        if ([contentUrl length] != 0) {
            request.contentURL = contentUrl;
        }
    }

    NSString *npaValue = GoogleAdMobAdapterConfiguration.npaString;
    
    if (npaValue.length > 0) {
        GADExtras *extras = [[GADExtras alloc] init];
        extras.additionalParameters = @{@"npa": npaValue};
        [request registerAdNetworkExtras:extras];
    }

    MPLogAdEvent([MPLogEvent adLoadAttemptForAdapter:NSStringFromClass(self.class) dspCreativeId:nil dspName:nil], [self getAdNetworkId]);
    
    [GADRewardedAd loadWithAdUnitID:self.admobAdUnitId
                            request:request
                  completionHandler:^(GADRewardedAd *ad, NSError *error) {
      if (error) {
          MPLogAdEvent([MPLogEvent adLoadFailedForAdapter:NSStringFromClass(self.class) error:error], [self getAdNetworkId]);
          [self.delegate fullscreenAdAdapter:self didFailToLoadAdWithError:error];
        
          return;
      }
        
      self.rewardedAd = ad;
      self.rewardedAd.fullScreenContentDelegate = self;
        
      MPLogAdEvent([MPLogEvent adLoadSuccessForAdapter:NSStringFromClass(self.class)], [self getAdNetworkId]);
      [self.delegate fullscreenAdAdapterDidLoadAd:self];
    }];
}
```

 5. **Wrap up**
 I fixed the bug temporary but didn't know why?  Can you help?

6. **Reference**
[libdispatch efficiency tips](https://gist.github.com/tclementdev/6af616354912b0347cdf6db159c37057)

**Comment by chauduyphanvu** [comment]
@chenxi141017, `startWithCompletionHandler` belongs to [Google's initialization API](https://github.com/mopub/mopub-ios-mediation/blob/master/AdMob/GoogleAdMobAdapterConfiguration.m#L64-L69) so you will need to let Google know on this forum: https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

Other than that, your workaround looks OK to me. 

Vu Chau
MoPub Team
