### ISSUE TITLE
Applovin SDK 10.3.0 is not available

### ISSUE THREAD

**Issue by bahattin-alictus** [mopub/mopub-ios-mediation#405]
1. **What is the issue?**
    > IOS pod generation fails for "MoPub-Applovin-Adapters : 10.3.0.0" [Applovin Notes](https://github.com/AppLovin/AppLovin-MAX-SDK-iOS/releases/tag/release_10_3_0) says they have removed the SDK.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Any
    * **Platform** (*Android, iOS, Unity*)
        > iOS, Unity
    * **MoPub SDK Version**
        > 5.17.0
    * **Mediation SDK Name & Version**
        > Applovin 10.3.0
    * **Mediation Adapter Version**
        > Applovin 10.3.0.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Any
    * **Device model and OS Version**
        > -
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Get the latest adapter dependencies from Mopub SDK Manager (iOS SDK : 10.3.0)
        > 2. Build for iOS
    * **Observed behavior**
        > curl: (22) The requested URL returned error: 403 for https://artifacts.applovin.com/ios/com/applovin/applovin-sdk/applovin-ios-sdk-10.3.0.zip
    * **Expected behavior** (if known)
        > Successful pods project (.xcworkspace) generation.
    * **Evidence** (if available)
        > 

> 
> [!] Error installing AppLovinSDK
> [!] /usr/bin/curl -f -L -o /var/folders/0v/swjlzg0n3h54q9nf1694mcxm0000gp/T/d20210618-27979-1qhlci2/file.zip https://artifacts.applovin.com/ios/com/applovin/applovin-sdk/applovin-ios-sdk-10.3.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'
> 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
> curl: (22) The requested URL returned error: 403
>

**Comment by p158276** [comment]
Hi @bahattin-alictus ,
Thanks for reaching out. AppLovin 10.3.2.0 adapter has been [released](https://github.com/mopub/mopub-ios-mediation/commit/767036a057ca4516cbf2d1f2b9da731b6b8d6cf8). Please let us know if you have any other question.

Yoyo Lin
MoPub Team

**Comment by p158276** [comment]
Hi @bahattin-alictus ,
If you are using our unity adapter, this is under our automation process queue.
Please check it again tomorrow. It should be available then.

**Comment by p158276** [comment]
Hi @bahattin-alictus ,
The AppLovin unity adapter build (1.8.5-Android.10.3.1.0-iOS.10.3.2.0) is available [here](https://firebasestorage.googleapis.com/v0/b/mopub-mediation.appspot.com/o/MoPub-AppLovin-Adapters-prod-1.8.5-Android.10.3.1.0-iOS.10.3.2.0.unitypackage?alt=media).  I'll close this issue here. Feel free to reopen if you have any question related to this. 

Yoyo Lin
MoPub Team
