### ISSUE TITLE
Facebook Advanced Bidding with Mopub Mediation

### ISSUE THREAD

**Issue by djrobinson999** [mopub/mopub-ios-mediation#507]
Hi I am having the same problem as this closed issue :

"Problem with Facebook audience network integration #408"

 and have tried the solutions suggested but still no requests are sent to Facebook. Bidding requests ARE sent to Mopub Marketplace tho. How can I tell where the messages are getting lost ? Can I check on the client side ?

_Originally posted by @djrobinson999 in https://github.com/mopub/mopub-ios-mediation/issues/408#issuecomment-910361666_

**Comment by chauduyphanvu** [comment]
@djrobinson999, to further confirm, could you test with this ad unit ID for iOS interstitial? **7bf46581fe9a4d548aef583a6ba018d9**. 

It should serve a test ad from Facebook for bidding, and in the device/console log you should see "Loading Facebook interstitial ad markup for Advanced Bidding". 

If that ad unit works, then it means your SDK/adapter integration is OK, and that you should double-check the Facebook placements.

If that ad unit doesn't work, then it means your SDK/adapter integration needs to be validated. Optionally, you could also share your ad unit IDs with us so we could test on our side.

Vu Chau
MoPub Team

**Comment by djrobinson999** [comment]
> @djrobinson999, to further confirm, could you test with this ad unit ID for iOS interstitial? **7bf46581fe9a4d548aef583a6ba018d9**.
> 
> It should serve a test ad from Facebook for bidding, and in the device/console log you should see "Loading Facebook interstitial ad markup for Advanced Bidding".
> 
> If that ad unit works, then it means your SDK/adapter integration is OK, and that you should double-check the Facebook placements.
> 
> If that ad unit doesn't work, then it means your SDK/adapter integration needs to be validated. Optionally, you could also share your ad unit IDs with us so we could test on our side.
> 
> Vu Chau
> MoPub Team

Hi thanks for getting back to me. That ad unit doesn't work for me. I get :

[MoPub][MPBannerAdManager][7bf46581fe9a4d548aef583a6ba018d9] Attempting to load ad
	{"ifa":"A2BDADEE-AC52-4FB4-8019-45906FBD54F1","z":"+0100","sc":"2.0","skadn_hash":"4d8c36cdefbecb56efea2d6505e295b07c30ed874435b2de940b2c4e68c6e257","hwv":"iPad","id":"7bf46581fe9a4d548aef583a6ba018d9","ats":"0","consented_privacy_policy_version":"2","skadn_last_send_ts":"1631026919","gdpr_applies":"1","vver":"1.3.16-Mopub","h":"2048","bundle":"dn":"iPad6,11","ce_settings_hash_key":"69bb43100d292fdb3b024d8fdb747b7373bb42743821195d2b0a58f303992393","make":"Apple","mr":"1","backoff_ms":"15000","adunit":"20ec5d7828a34271bfbdc51e92696c0a","av":"1.5.10","skadn_last_send_av":"1.5.10","model":"iPad6,11","o":"p","ct":"2","vv":"4","osv":"14.7.1","las":"unknown","ifv":"7983056B-F17A-4F35-B55B-EDCB9FF31FAB","consented_vendor_list_version":"2","os":"ios","mid":"7068BDE1-055A-4107-9658-43A45E559ADA","ch":"180","cw":"1536","nv":"5.18.0","v":"8","current_consent_status":"explicit_yes","force_gdpr_applies":"0","tas":"authorized","w":"1536","abt":"{\"facebook\":{\"token\":\"eJx9VFGPmzgQ\\\/iuIp1YCYhMTSKp7MNgkFGJzQJLdlpPFbqiKQjerbapqr+p\\\/vxk2vdU99B4YeezxzDfzfeaHzZVWJhP2yr75QGIWRQGhLiVJ5DLuJ+4yoXM35iIMYiIXviS2Y\\\/O0hPCu849HdOukklKZQyaajb0KF5Fjx5kQsjKNzuFA3jQVr+HGj9YeHlt71dqURZ4f+B6dwxdGrf0T8qQ7pWRhCr1eS8DzqRu\\\/9o5dad2gSx270AkvJCTqH8w6hhuZSLlJC76GPUSyU1lza68IQFSmzg0XRsnmoKscy0OA4A03ZaUTWdeZWhtdNplWtakb3mDih2\\\/jCGFbKTKOJ6aW1T5L8Giry11sAo9GHlktvIVHPCwZ75SYMCXD5Vk8nYejt+2+fAHs+lP8NFy64eF\\\/6iZ6p5rq9rWykKqeerB98DTCHsD+O5xEV9LIvVQNHjFKqMMoW4DxQzBkWs1xxRwGFo2PhiJvZRnvsgK5pl7gsTmODDo0fA0Jscfz38M4du0s8Ij1Zii74zsrKXeWri3KTGioNQ6n3tp297h189bij49jf+jv8uHSzhYEpuPRwHqTb5pt4bwEr\\\/v70\\\/mttT3fDWPfzmgggXzrYxpz1c74t+PQP9z3qr98Pz+d0vMTdPsujcW+nWH5hUMpuFvRzt6H9MJLcGq49xJVQxRlXuhhTJG0s0kXsN7XgAYpgjWP29nvucEAzALjoBgdXx02\\\/wt1oIUskIIrFOSb19LUIjd7WdXAIc6SeQEG8xx1MI0EX4XI8eb5K6yvIjTNbSknJf83wQT19yp5VQdeS3jJ46x4EclHoNoJnNBZOsA1ME0BZujQCNEXmcqlgHfZbEymawMUauA61nvEic1sDbCgQAC5xGx\\\/+iPpd9XznT+eihP9fHeAb6PKD6f3z91N9bk7sD9e3\\\/tGZusNqIYSn8EmYv71J2FhQkI2910azQOXiWDuLn05d6mMU8ojOE7E9fnixPxYcCGly5PAd1kaMzcidOmyYEkWoIWApVf14siu4qVkeh+\\\/diYV2D\\\/\\\/ASpaRdY=\"}}","backoff_reason":"unfilled"}
	[MoPub][MPBannerAdManager] No ads found for ad unit: 7bf46581fe9a4d548aef583a6ba018d9

Interestingly I get Requests to both Mopub and Facebook showing on the Mopub Bidding console for my ad unit but no impressions and no requests show on the Facebook console (although non bidding requests to the FAN do work).

If you want to know my ad unit can I contact you offline ?

Regards

David

**Comment by chauduyphanvu** [comment]
Hello, **7bf46581fe9a4d548aef583a6ba018d9** is an interstitial ad unit ID. I see you were trying with banner. Could you retry with interstitial?

Thanks.

**Comment by djrobinson999** [comment]
Hi, I get the same with an interstitial :

[MoPub][MPAdServerCommunicator] Requesting an ad from Adserver: https://ads.mopub.com/m/ad
	{"z":"+0100","skadn_hash":"4d8c36cdefbecb56efea2d6505e295b07c30ed874435b2de940b2c4e68c6e257","hwv":"iPad","id":"7bf46581fe9a4d548aef583a6ba018d9","ats":"0","consented_privacy_policy_version":"2","skadn_last_send_ts":"1631289216","gdpr_applies":"1","vver":"1.3.16-Mopub","h":"2160","bundle":"*******","dn":"x86_64","ce_settings_hash_key":"69bb43100d292fdb3b024d8fdb747b7373bb42743821195d2b0a58f303992393","make":"Apple","mr":"1","adunit":"20ec5d7828a34271bfbdc51e92696c0a","av":"1.5.10","skadn_last_send_av":"1.5.10","model":"x86_64","o":"p","ct":"2","vv":"4","osv":"14.5","las":"unknown","ifv":"4A777D75-E9ED-45C2-B235-FE518F68AA21","consented_vendor_list_version":"2","os":"ios","mid":"3D06A94F-E57D-4ABC-93E9-5B5F46369DBE","ch":"2120","cw":"1620","nv":"5.18.0","v":"8","current_consent_status":"explicit_yes","force_gdpr_applies":"0","tas":"authorized","w":"1620","abt":"{\"facebook\":{\"token\":\"eJx9VG1vmzAQ\\\/iuIT6tECAbz0lT7YLBJGMRmGJJ2ZbJoyzQUmlRdp62b9t93JqmqSduQOPnM4\\\/PdPc\\\/x0yRccJVRc2FefgjcKHQCFs2IT+IZJu75LA49d+YGDvKSKI4SPzItk6QlwLu70A1vwZVJxRhX24zWK3MRIccy44xSVqla5PCBXdYVkXDiZ2sOD625aE2EI9v1XRt58IZRa\\\/6COGnDOStUIZZLBvl86sYvvWVWQtTaRZZZiIQUDAL1e9VIOJHRlKi0IEvYQ+A3PKuvzAUkQLiSuSJUcVZvRZXr6wFASU1UWYmESZnxpRJlnQkulaxJrQPvv44jwBJSloxCV\\\/Sx64+ws2Y0IxqrJKs2WaLBa1E2sfJtFNnOIrAD27EdgMYNp1OWyfD0TB8Pw5297u7voRrxKX4cnrph\\\/59MEtHwurp6zYUyLqeqTBc8oTMahHxtVyIqptiG8Vp\\\/wshBFkY4AOOGYJxp5ekVtjBYbVxtdMOgzrjJCs0+sn0be7qJUKEiSwioazz8GMaxa+e+7RhvhrK7uzCSsjGENBBWvjEOu95Yd7d64\\\/LMIA8PY7\\\/tb\\\/LhqZ0HDvTGRr7xJl\\\/V68I6gpf97e5wZqwPN8PYt3PkMxCDcZ3GhLdz8vVu6Pe3Pe+fvh0ed+nhEWq9SGO6aeffo0AFGJw1bedw5f2wHyILwYaEk0ecBBzCtg\\\/LImnnk05gvZGQjSYI1iRu5\\\/9mRgN0DGgG0uj45GBvUoGgrICuHFPRXBPJlKS52rBKAn+6j3C9hpJca2BqiJ4RmmviDl9gfZKkqq9KNun6zwBTov9WyKsy9DFQKomz4iiQa6DZ8q3QOreAZ2AZBRYKLRTp3IuM56DpbVavVCakAvoE8ByLDTtNz1oBBxzIz5mO9t4dnb6pnm\\\/ccVfs0OebLbwrXn7YvXvuLqvP32021-09-10 17:02:48.591740+0100 MammalsOfBritain[65604:2701742] viewDidLoad started : Mammal :  : Search:
	[MoPub][MPAdServerCommunicator] Adserver responded with:
	[MoPub][MPInterstitialAdManager] Interstitial ad view is fetching ad type: clear
	[MoPub][MPInterstitialAdManager] No ads found for ad unit: 7bf46581fe9a4d548aef583a6ba018d9

**Comment by chauduyphanvu** [comment]
@djrobinson999, thank you for the confirmation. You should see a Facebook test ad like so (this is simulated from the MoPub iOS sample app):

![image](https://user-images.githubusercontent.com/25616035/132916594-73826472-a598-49cf-9b40-5d4ed55ab7d9.png)

If you are consistently not getting any ads, even with the test ad unit ID I shared, there might have been something wrong in your SDK/adapter integration with Facebook Audience Network. Which versions of the FAN SDK and adapters are you using in your app?

Additionally, as another means of verification, you can also test your own ad unit IDs in MoPub's sample app: https://github.com/mopub/mopub-ios-sdk/tree/master/Canary. If they work, then that further confirms that we need to look at your SDK/adapters integration.

**Comment by SodaSurfer** [comment]
Hi, unfortunately it still not working for me... \: 
I probably would give it another month to try and solve it, otherwise I'm thinking to stop working with Mopub and try to use Admob, even though it's my last resort..

**Comment by djrobinson999** [comment]
> Hi, unfortunately it still not working for me... :
> I probably would give it another month to try and solve it, otherwise I'm thinking to stop working with Mopub and try to use Admob, even though it's my last resort..

Did you try what chauduyphanvu suggested with the MoPub sample app ? I did but couldn't get anywhere so far.

Disappointing that there are such issues here. Always a problem when two systems/companies are involved and us end users end up stuck in the middle.

**Comment by djrobinson999** [comment]
Sorry closed in error.

**Comment by chauduyphanvu** [comment]
@djrobinson999, @SodaSurfer, hi all, as a way to confirm where this issue exists, I previously asked to check your ad unit IDs in the MoPub sample app. Did they work?

We need to know what your result is before we can advise on next steps. We can't help you if we don't see the issue in action.

**Comment by djrobinson999** [comment]
Hi 

> @djrobinson999, @SodaSurfer, hi all, as a way to confirm where this issue exists, I previously asked to check your ad unit IDs in the MoPub sample app. Did they work?
> 
> We need to know what your result is before we can advise on next steps. We can't help you if we don't see the issue in action.

I can't even get your sample Canary app to load Facebook ads : 

2021-09-28 10:36:05.777929+0100 Canary[40045:766998] 
	[MoPub][MPInterstitialAdManager][7bf46581fe9a4d548aef583a6ba018d9] Attempting to load ad
2021-09-28 10:36:06.002307+0100 Canary[40045:766998] 
	[MoPub][MPInterstitialAdManager] Interstitial ad view is fetching ad type: clear
2021-09-28 10:36:06.002413+0100 Canary[40045:766998] 
	[MoPub][MPInterstitialAdManager] No ads found for ad unit: 7bf46581fe9a4d548aef583a6ba018d9

So I am a bit stuck.

**Comment by SodaSurfer** [comment]
> @djrobinson999, @SodaSurfer, hi all, as a way to confirm where this issue exists, I previously asked to check your ad unit IDs in the MoPub sample app. Did they work?
> 
> We need to know what your result is before we can advise on next steps. We can't help you if we don't see the issue in action.

Hi I really appreciate your help and I don't have any complains to you.
Indeed you tried a lot to help me, but it didn't work.
My implementation with your sample ad worked for me so my problem I guess on the Facebook setup side, though Facebook ads support team is very not helpful and they just refer me to their debug page.
I know this is not your problem, but as long as you, as Mopub side, won't try to help us, the developers, also to setup the ads in the right way through the Facebook side, then your integration won't matter, if no one would be able to set it on the Facebook side, therefore I still think you also have an interest to try and help others to setup the ads on the Facebook side as well.

Thanks

**Comment by chauduyphanvu** [comment]
@djrobinson999, @SodaSurfer - I wonder if this is related to https://github.com/mopub/mopub-unity-sdk/issues/207#issuecomment-930563933. Are you able to confirm that recommendation?

**Comment by djrobinson999** [comment]
> @djrobinson999, @SodaSurfer - I wonder if this is related to [mopub/mopub-unity-sdk#207 (comment)](https://github.com/mopub/mopub-unity-sdk/issues/207#issuecomment-930563933). Are you able to confirm that recommendation?

Hi, yes my device has the Facebook app loaded and is logged in fine.

I still can't get your Canary app to work with your test Ad Unit Id on a device with Facebook working : 

2021-09-28 10:36:05.777929+0100 Canary[40045:766998]
[MoPub][MPInterstitialAdManager][7bf46581fe9a4d548aef583a6ba018d9] Attempting to load ad
2021-09-28 10:36:06.002307+0100 Canary[40045:766998]
[MoPub][MPInterstitialAdManager] Interstitial ad view is fetching ad type: clear
2021-09-28 10:36:06.002413+0100 Canary[40045:766998]
[MoPub][MPInterstitialAdManager] No ads found for ad unit: 7bf46581fe9a4d548aef583a6ba018d9

Why would this be ? Isn't this Ad Unit a test one ? It should always reply with a test ad surely. 

My issue is that there is nothing I can do as the replies come from your system and only logging of what is happening at your end will help.

I can work with you via PM if you like to get this sorted.

**Comment by chauduyphanvu** [comment]
@djrobinson999, yes, feel free to reach out via [my Twitter](https://twitter.com/chauduyphanvu) for additional assistance.

I also recommend turning on [debug logging](https://github.com/mopub/mopub-ios-sdk/blob/master/Canary/Canary/SceneDelegate.swift#L276) so we might see extra details.

**Comment by djrobinson999** [comment]
> @djrobinson999, yes, feel free to reach out via [my Twitter](https://twitter.com/chauduyphanvu) for additional assistance.
> 
> I also recommend turning on [debug logging](https://github.com/mopub/mopub-ios-sdk/blob/master/Canary/Canary/SceneDelegate.swift#L276) so we might see extra details.

I have PM'd you on Twitter.

**Comment by SodaSurfer** [comment]
@djrobinson999 @chauduyphanvu please update this issue if you managed to solve the problem

**Comment by djrobinson999** [comment]
> @djrobinson999 @chauduyphanvu please update this issue if you managed to solve the problem

Hi, yes will do.
