### ISSUE TITLE
Verizon Advanced Bidding Banner doesn't sent 'click' and 'display' fields on

### ISSUE THREAD

**Issue by n3ir0** [mopub/mopub-ios-mediation#529]
1. **What is the issue?**
    > Provide a one-line summary of the issue here.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ x] I searched https://developers.mopub.com/ and found no answer.
    - [ x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        Advanced Bidding Banner
    * **Platform** (*Android, iOS, Unity*)
        iOS
    * **MoPub SDK Version**
       5.17.0
    * **Mediation SDK Name & Version**
        Verizon 1.14.1.0
    * **Mediation Adapter Version**
        Using MPVerizonBannerCustomEvent.m 1.13.0.0 
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        0f07d109c1644ac89dad146c6d6f52fe
    * **Device model and OS Version**
        iPhone 11 iOS 14.2+
    * **Steps to reproduce the issue** (include integration steps if not standard)
        Get and show Verizon  Advanced Bidding Banner
        Click it and look at response on https://ads.nexage.com/admax/sdk/report/5?dcn=8a809417014f4ef6290702792dd900cf
    * **Observed behavior**
        There are no fields 'click' and 'display' 
{
	"req": [{
		"ts": 1632763719040,
		"resp": 0,
		"adnet": [{
			"tag": "2c9d2b5001656511806014dd2ded000f",
			"status": 110,
			"resp": 0
		}],
		"zone": "mrec_sa_1",
		"a": "6cc4c2affb104bb183bdb652c021c34a"
	}, {
		"ts": 1632763719047,
		"resp": 0,
		"adnet": [{
			"tag": "2c9d2b4f016363008abc077c3a170066",
			"status": 110,
			"resp": 0
		}],
		"zone": "banner_sa_1",
		"a": "18e0cee851ab439b8498f36466572e26"
	}, {
		"ts": 1632763720700,
		"resp": 0,
		"adnet": [{
			"tag": "2c9d2b5001656511806014dd2ded000f",
			"status": 110,
			"resp": 0
		}],
		"zone": "mrec_sa_1",
		"a": "ab657df7093b44ddb652f3c2aa04fa79"
	}, {
		"ts": 1632763721144,
		"resp": 0,
		"adnet": [{
			"tag": "2c9d2b4f016363008abc077c3a170066",
			"status": 110,
			"resp": 0
		}],
		"zone": "banner_sa_1",
		"a": "9957cbf519cd42178e54b181c17ba2f8"
	}]
}
    * **Expected behavior** (if known)
    There fields 'click' and 'display' 
        {
	"req": [{
		"ts": 1632766386478,
		"resp": 0,
		"adnet": [{
			"tag": "2c9d2b4f016363008abc077c3a170066",
			"status": 110,
			"resp": 0
		}],
		"zone": "banner_sa_1",
		"a": "2518e575924b4b58a8c4ed9bb1e52b7d"
	}, {
		"ts": 1632766387883,
		"resp": 567,
		"adnet": [{
			"tag": "2c9d2b500161610a94d41031da630173",
			"status": 1,
			"resp": 567
		}],
		"zone": "banner_sdk_test",
		"a": "9852aa80e25d4ecaaec94296633bdacc"
	}],
	"display": [{
		"ts": 1632766386156,
		"zone": "banner_sdk_test",
		"tag": "2c9d2b500161610a94d41031da630173",
		"a": "b95b274a3403458e88ec45b014536d2b"
	}],
	"click": [{
		"ts": 1632766366606,
		"zone": "banner_sdk_test",
		"tag": "2c9d2b500161610a94d41031da630173",
		"a": "92cc9b2d12f94c10911dde79eaa12fa6"
	}, {
		"ts": 1632766396401,
		"zone": "banner_sdk_test",
		"tag": "2c9d2b500161610a94d41031da630173",
		"a": "9852aa80e25d4ecaaec94296633bdacc"
	}]
}
    * **Evidence** (if available)

**Comment by chauduyphanvu** [comment]
@n3ir0, thanks for the report. Could you elaborate on what the impact of this behavior is?
