### ISSUE TITLE
Screen becomes unresponsive during game

### ISSUE THREAD

**Issue by egorafanasenko** [mopub/mopub-ios-mediation#530]
1. **What is the issue?**
After application start, the game becomes unresponsive. I am unable to click anywhere on the screen.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        Not related to an Ad Format
    * **Platform** (*Android, iOS, Unity*)
        iOS
    * **MoPub SDK Version**
        5.18.0
    * **Mediation SDK Name & Version**
        AdColony 4.7.2
    * **Mediation Adapter Version**
        MoPub-AdColony-Adapters  4.7.2.0
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Provide the data here
    * **Device model and OS Version**
        iPhone 12 & iOS 15 (but looks like any iOS device)
    * **Steps to reproduce the issue** (include integration steps if not standard)
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
 AdColony [Info] -[ADCDevice init]_block_invoke Line 640 : ADCNetwork status change: 1
 AdColony [Info] -[ADCNativeLayer sendMessage:] Line 344 : Attempted to send an Network.on_status_change message to an unknown ADCModule with id: 1

**Comment by dravyan** [comment]
@egorafanasenko, I tried testing with 4.7.2.0 AdColony adapters and I do not notice any screen hang behavior with it. I am able to load and show the ads just fine. Can you reproduce the issue with the [MoPub sample app](https://github.com/mopub/mopub-ios-sdk/tree/master/Canary)? Could you share the screen recording and complete device logs to look into it further?

Thanks,
MoPub Team
