### ISSUE TITLE
[Facebook] missing fbPlacementId setup in FacebookRewardedVideoCustomEvent

### ISSUE THREAD

**Issue by kevinchailloux** [mopub/mopub-ios-mediation#536]
1. **What is the issue?**
The variable `fbPlacementId` is not set but is used in the event reporting inside the file FacebookRewardedVideoCustomEvent.m.
https://github.com/mopub/mopub-ios-mediation/blob/master/FacebookAudienceNetwork/FacebookRewardedVideoCustomEvent.m

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [X] I searched https://developers.mopub.com/ and found no answer.
    - [X] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [X] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > RewardedVideo
    * **Platform** (*Android, iOS, Unity*)
        > iOS
    * **MoPub SDK Version**
        > Does not matter
    * **Mediation SDK Name & Version**
        > Facebook Audience Network the version is irrelevant
    * **Mediation Adapter Version**
        > Any version I've seen for the past 6 months.
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Any id that triggers a Facebook request
    * **Device model and OS Version**
        > Not device dependent
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Request a rewarded video from a placement linked to a Facebook placement.
        > 2. Check the value inside `FacebookRewardedVideoCustomEvent` of the field `fbPlacementId`
    * **Observed behavior**
        > This value is never set but is used in many places to send log to the MoPub system.
    * **Expected behavior** (if known)
        > The line `self.fbPlacementId = [info objectForKey:@"placement_id"];` should be present inside the `requestAdWithAdapterInfo` method.
    * **Evidence** (if available)
        > There is no line in the class that set this value.

**Comment by chauduyphanvu** [comment]
@kevinchailloux, thanks for the report. We will take a look.

Vu Chau
MoPub Team
