### ISSUE TITLE
The podspecs are configured to always bring the latest master code

### ISSUE THREAD

**Issue by polmum** [mopub/mopub-ios-mediation#76]
There is no way to add a dependency in the Podfile to an old version of an adapter because the podspec is configured to always bring the latest master commit.

For example, the MoPub-AdColony-Adapters.podspec is configured as follows:
`s.source           = { :git => 'https://github.com/mopub/mopub-ios-mediation.git', :commit => 'master' }`

**Comment by polmum** [comment]
We tried using `pod 'MoPub-FacebookAudienceNetwork-Adapters', '4.28.1.2' `, expecting it to bring the version that is adapting FacebookAudienceNetwork `4.28.1`, but we found that it is actually bringing the latest code in master, which corresponds to the `4.99.1` version.

**Comment by mshrwtnb** [comment]
@chauduyphanvu1 
having the same issue.
any update on this?

**Comment by chauduyphanvu1** [comment]
Hi, there currently is no update on this issue yet, but we should be able to get to it soon! In the meantime, please utilize the adapter binaries available on this GitHub repo to find any historical releases you might need.

**Comment by mshrwtnb** [comment]
@chauduyphanvu1 
Is there anyway I can download this specific ver?
> MoPub-FacebookAudienceNetwork-Adapters (4.28.0.1)

**Comment by chauduyphanvu1** [comment]
@mshrwtnb - FB 4.28.0.1 can be found in https://github.com/mopub/mopub-ios-mediation/commit/709e6b520941cd34d088c279b5343b87f6452c25. The adapter binary that changed was `FacebookNativeAdAdapter.m`. To see the other FB binaries, check out https://github.com/mopub/mopub-ios-mediation/tree/709e6b520941cd34d088c279b5343b87f6452c25.

**Comment by chauduyphanvu1** [comment]
Closing as there was an short-term workaround.

**Comment by polmum** [comment]
I disagree with closing this issue just because there is a workaround.
We need to add a new adapter, but one that is not the latest version, and we once again are unable to do so via cocoapods because the podspec is configured to always bring master, instead of a tag or specific commit.
Pods defined this way are unreliable and prone to error, so I think this should be fixed.

**Comment by rsatrasala** [comment]
Thank you @polmum. We will explore maintaining branches per release per network and see how we can maintain pods per release. We will get back to you with more updates in the next two weeks.

**Comment by stopiccot** [comment]
Do not explore branches. Just use git tags as described in official cocoapods manual https://guides.cocoapods.org/syntax/podspec.html

**Comment by stopiccot** [comment]
It's a 30min task not a two week one.

**Comment by chauduyphanvu1** [comment]
Via https://github.com/mopub/mopub-ios-mediation/commit/441be9a9b765e20f6564faef1673819d18c3d62d, all adapters have been set to use tags from this point going forward. For the full list of tags available, please check out https://github.com/mopub/mopub-ios-mediation/tags. Publishers will be adding adapters to their Podfile like so: `pod 'MoPub-[Network]-Adapters', 'network-1.2.3.4'`.

For releases older than today, publishers should continue fetching adapters via specific commits. Thanks!
