### ISSUE TITLE
Facebook Audience Network dont show images 

### ISSUE THREAD

**Issue by vexelgray** [mopub/mopub-ios-mediation#92]
Hello,

I think there is a bug with the new Facebook adapter.

The adapter shows images (nativePrivacyInformationIconImageView, nativeIconImageView and nativePrivacyInformationIconImageView) using **MPCollectionViewAdPlacer** but it can't display images using **MPTableViewAdPlacer**.

Im using other adapters like Flurry, AOL, Appnext and they shows images and texts in CollectionViews and TableViews but Facebook adapter can't show images in Tableviews.

Anyone else have this problem?

**Comment by chauduyphanvu1** [comment]
@vexelgray - thanks for the report. 

- Are you able to reproduce that issue in the MoPub sample app? 
- Could you confirm which version of the MoPub SDK, the FB SDK, and the FB adapters you are using?

**Comment by vexelgray** [comment]
Thank you @chauduyphanvu1 

Im using:

- FBAudienceNetwork (4.99.2)
- MoPub-FacebookAudienceNetwork-Adapters (4.99.2.1)
- Mopub-ios-sdk (5.3.0)

This versions are installed using _pod 'MoPub-FacebookAudienceNetwork-Adapters'_

It seems this pod does not use FB 5.0.0...

Regards!

**Comment by vexelgray** [comment]
Trying to install a branch called **vchau-fb-5.0.0.0** that it has FB 5.0.0...

Pre-downloading: `MoPub-FacebookAudienceNetwork-Adapters` from `https://github.com/mopub/mopub-ios-mediation.git`, branch `vchau-fb-5.0.0.0`
[!] Unable to find a specification for 'MoPub-FacebookAudienceNetwork-Adapters'

**Comment by chauduyphanvu1** [comment]
The pod that'd pull FB 5.0.0 is not live yet (it's still bring certified), but you can drop their 5.0.0 framework to our sample project to confirm. Meanwhile, I'll also test out the version we have live right now.

**Comment by chauduyphanvu1** [comment]
I still couldn't reproduce the issue using your configuration:

> FBAudienceNetwork (4.99.2)
> MoPub-FacebookAudienceNetwork-Adapters (4.99.2.1)
> Mopub-ios-sdk (5.3.0)

Here's the MoPub sample project I modified to mediate FB native ads via the TableView AdPlacer: https://s3.us-east-2.amazonaws.com/chauduyphanvu/sample_apps/mopub-ios-sdk-with-fb-4.99.2.zip. Feel free to send across your project to support@mopub.com for assistance!

**Comment by vexelgray** [comment]
Ok @chauduyphanvu1, i found the bug.

I need cells with dynamic heigh, because nativeMainTextLabel is different on each ad. I've been trying to find a way to implement a dynamic cell height but all the sample app, instructions provided by mopub only shows the static height implementation.

I've found a workaround but it relies on a constant not exposed by the MoPub SDK interface.

If you look at MPStreamAdPlacer

```
- (CGSize)sizeForAd:(MPNativeAd *)ad withMaximumWidth:(CGFloat)maxWidth andIndexPath:(NSIndexPath *)indexPath
{
    id<MPNativeAdRenderer> renderer = ad.renderer;

    CGSize adSize;

    if ([renderer respondsToSelector:@selector(viewSizeHandler)] && renderer.viewSizeHandler) {
        adSize = [renderer viewSizeHandler](maxWidth);
        if (adSize.height == MPNativeViewDynamicDimension) {
            UIView *adView = [ad retrieveAdViewForSizeCalculationWithError:nil];
            if (adView) {
                CGSize hydratedAdViewSize = [adView sizeThatFits:CGSizeMake(adSize.width, CGFLOAT_MAX)];
                return hydratedAdViewSize;
            }
        }
        return adSize;
    }

    adSize = CGSizeMake(maxWidth, 44.0f);
    MPLogWarn(@"WARNING: + (CGSize)viewSizeHandler is NOT implemented for native ad renderer %@ at index path %@. You MUST implement this method to ensure that ad placer native ad cells are correctly sized. Returning a default size of %@ for now.", NSStringFromClass([(id)renderer class]), indexPath, NSStringFromCGSize(adSize));

    return adSize;
}
```

This method is called by MPTableViewAdPlacer to get the size for the ad. It in turn uses the viewSizeHandler you set when configuring your placer. Notice that if the returned height is equal to MPNativeViewDynamicDimension (-1.0) then it falls back to calling **-sizeThatFits: on the ad view.**

At this point the ad view has been configured with the data from the ad server so you can implement  -sizeThatFits: and return a size appropriate for the content:

```
// MoPub setup

MPStaticNativeAdRendererSettings *settings = [[MPStaticNativeAdRendererSettings alloc] init];
settings.renderingViewClass = [MyAdView class];
settings.viewSizeHandler = ^(CGFloat maxWidth) {
    return CGSizeMake(maxWidth, -1.0);
};
```

MyAdView class:

```
- (CGSize)sizeThatFits:(CGSize)size {
    
    // Inspect the configured labels and images to determine appropriate height for given size.width
    
    return CGSizeMake(size.width,  110.0f + [self getLabelHeight:self.mainTextLabel]);
}
```

While the method works for the stock MoPub Marketplace adapters, I've found a bug in MoPub's SDK that can cause issues with other adapters. Specifically, Facebook's imageviews won't appear if you use this method.

So.. this method is working well with all native adapters but not with facebook adapter, so... is there some solution to have dynamic cell height or is a Facebook adapter bug?

Could you test it @chauduyphanvu1 ?

**Comment by chauduyphanvu1** [comment]
@vexelgray, thanks for the additional investigation! Could you create a branch/PR that has a demo so we could see that issue in action? The MoPub iOS SDK is at https://github.com/mopub/mopub-ios-sdk if you need it.

**Comment by vexelgray** [comment]
@chauduyphanvu1, thanks for your reply. I developed an example where you can see the bug with Facebook ads. You can take a look here: https://github.com/vexelgray/mopubFB
 
You can see the problem in this photos, ads from mopub's marketplace are working well with dynamic height, but facebook ads with dynamic height don't show the images:

![img_0087](https://user-images.githubusercontent.com/1415826/46245888-1cf52880-c3f6-11e8-9c18-5f7c9d8a5f62.PNG)
![img_0086](https://user-images.githubusercontent.com/1415826/46245889-1cf52880-c3f6-11e8-91c4-f95ff16a098f.PNG)

Hoper your answer 👍 

Regards
